import { Theme } from "../../../def.slint";
import { IconBtn, Divider, Label } from "../../../../base/widgets.slint";

export component MoveHandle inherits Rectangle {
    out property mouse-x <=> ta.mouse-x;
    out property mouse-y <=> ta.mouse-y;
    out property pressed-x <=> ta.pressed-x;
    out property pressed-y <=> ta.pressed-y;
    out property pressed <=> ta.pressed;
    in-out property enabled <=> ta.enabled;
    in-out property <int> index;
    in-out property <string> text;
    in-out property <bool> hide-center-point;
    in-out property <color> enabled-handle-color: Colors.white;
    in-out property <color> disabled-handle-color: Theme.danger-color;

    callback moved <=> ta.moved;
    callback clicked <=> ta.clicked;
    callback released;
    callback pressed-changed;

    pure function mouse-cursor(index: int) -> MouseCursor {
        if (index == 1) {
            return MouseCursor.nw-resize;
        } else if (index == 2) {
            return MouseCursor.ne-resize;
        } else if (index == 3) {
            return MouseCursor.se-resize;
        } else {
            return MouseCursor.sw-resize;
        }
    }

    width: Theme.icon-size * 2;
    height: self.width;
    border-radius: self.width / 2;

    if !hide-center-point: Rectangle {
        width: Theme.icon-size * 0.5;
        height: self.width;
        border-radius: self.width / 2;
        background: root.enabled ? enabled-handle-color : disabled-handle-color;
    }

    if !text.is-empty: Label {
        text: root.text;
        font-size: parent.width * 0.8;
        color: Theme.light-text-color;
    }

    ta := TouchArea {
        mouse-cursor: self.enabled ? (hide-center-point ? pointer : mouse-cursor(index)) : not-allowed;

        changed pressed => {
            if (self.pressed) {
                root.pressed-changed();
            } else {
                root.released();
            }
        }
    }
}
