import {
    Theme,
    Store,
    Logic,
    Util,
    Icons,
    VideoPreviewSize,
    VideoEditorLayerImage,
    LocalMagnifyDetail,
} from "../../../def.slint";
import { VEFilter, FilterType } from "../filter.slint";
import { IconBtn, Divider, Label } from "../../../../base/widgets.slint";
import { MoveHandle } from "move-handle.slint";

export component PreviewLocalMagnifyLayer inherits Rectangle {
    in-out property <[VideoEditorLayerImage]> layers;
    private property <float> width-hight-rate: self.width / self.height;
    private property <FilterType> selected-filter-type <=> VEFilter.selected-filter.ty;

    for index in layers.length: rec := Rectangle {
        x: 0;
        y: 0;

        private property <VideoEditorLayerImage> layer: layers[layers.length - 1 - index];
        private property <bool> is-edited-track: Store.video-editor-current-edited-track-index == layer.track-index;
        private property <bool> has-keyframes: Logic.video-editor-segment-has-keyframes(layer.track-index, layer.segment-index);
        private property <LocalMagnifyDetail> config: is-edited-track && has-keyframes ? VEFilter.from-local-magnify-json(VEFilter.selected-filter.detail) : layer.local-magnify;
        private property <bool> is-previewing: Store.video-editor-is-previewing;

        changed is-previewing => {
            if (is-edited-track && !is-previewing && has-keyframes) {
                VEFilter.modify-local-magnify-filter(VEFilter.selected-filter-index, config, selected-filter-type);
            }
        }

        container-rec := Rectangle {
            width: img.width;
            height: img.height;

            img := Image {
                private property <length> parent-width: rec.width;
                private property <length> parent-height: rec.height;
                private property <float> width-hight-rate: self.source.width / self.source.height;

                changed parent-width => {
                    self.update-size();
                }

                changed parent-height => {
                    self.update-size();
                }

                function update-size() {
                    if (root.width-hight-rate > self.width-hight-rate) {
                        self.height = root.height;
                        self.width = self.height * self.width-hight-rate;
                    } else {
                        self.width = root.width;
                        self.height = self.width / self.width-hight-rate;
                    }
                }

                init => {
                    self.update-size();
                }

                source: layer.original-image;
                image-fit: ImageFit.contain;
            }

            if is-edited-track: Rectangle {
                width: img.width;
                height: img.height;

                selection-output-rec := Rectangle {
                    x: config.center-x * parent.width - self.width / 2;
                    y: config.center-y * parent.height - self.height / 2;
                    width: selection-rec.width * config.scale;
                    height: self.width;
                    border-radius: self.width / 2;
                    border-width: 2px;
                    border-color: white;
                }

                selection-rec := Rectangle {
                    x: config.center-x * parent.width - self.width / 2;
                    y: config.center-y * parent.height - self.height / 2;
                    width: VEFilter.scale-pixel-for-resolution(config.selection-radius, img.height / 1px) * 2px;
                    height: self.width;
                    border-radius: self.width / 2;
                    border-width: VEFilter.scale-pixel-for-resolution(config.border-width, img.height / 1px) * 1px;
                    border-color: rgba(config.border-color-r, config.border-color-g, config.border-color-b, config.border-color-a / 255.0);

                    TouchArea {
                        private property <bool> can-move;

                        pointer-event(event) => {
                            if (event.button == PointerEventButton.left) {
                                if (event.kind == PointerEventKind.down) {
                                    can-move = true
                                } else if (event.kind == PointerEventKind.up) {
                                    can-move = false;
                                    VEFilter.modify-local-magnify-filter(VEFilter.selected-filter-index, config, selected-filter-type);
                                }
                            }
                        }

                        moved => {
                            if (!can-move) {
                                return;
                            }
                            let x = clamp(parent.x + self.mouse-x - self.pressed-x, 0, img.width - parent.width);
                            let y = clamp(parent.y + self.mouse-y - self.pressed-y, 0, img.height - parent.height);
                            config.center-x = (x + parent.width / 2) / img.width;
                            config.center-y = (y + parent.height / 2) / img.height;
                        }
                    }

                    radius-handle := Rectangle {
                        x: parent.width - self.width / 2;
                        y: parent.height / 2 - self.height / 2;
                        background: white;
                        width: Theme.icon-size;
                        height: self.width;
                        border-radius: self.width / 2;
                        border-color: Theme.have-read-text-color;
                        border-width: Theme.default-border-width;

                        private property <bool> can-move;

                        TouchArea {
                            mouse-cursor: MouseCursor.ew-resize;

                            pointer-event(event) => {
                                if (event.button == PointerEventButton.left) {
                                    if (event.kind == PointerEventKind.down) {
                                        can-move = true
                                    } else if (event.kind == PointerEventKind.up) {
                                        can-move = false;
                                        VEFilter.modify-local-magnify-filter(VEFilter.selected-filter-index, config, selected-filter-type);
                                    }
                                }
                            }

                            moved => {
                                if (!can-move) {
                                    return;
                                }
                                config.selection-radius = clamp(config.selection-radius * 1px + self.mouse-x - self.pressed-x, 0, img.width >= img.height ? img.height : img.width) / 1px;
                            }
                        }
                    }
                }
            }
        }
    }
}

