[package]
name = "wayshot"
build = "build.rs"
license.workspace = true
edition.workspace = true
version.workspace = true
readme.workspace = true
authors.workspace = true
keywords.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
log.workspace = true
lru.workspace = true
bot.workspace = true
term.workspace = true
mp4m.workspace = true
open.workspace = true
rand.workspace = true
wrtc.workspace = true
toml.workspace = true
hound.workspace = true
paste.workspace = true
infer.workspace = true
cutout.workspace = true
pmacro.workspace = true
anyhow.workspace = true
camera.workspace = true
hf-hub.workspace = true
fast2s.workspace = true
chrono.workspace = true
silero.workspace = true
ttfx-rs.workspace = true
reqwest.workspace = true
speakrs.workspace = true
tempfile.workspace = true
recorder.workspace = true
lighting.workspace = true
crossbeam.workspace = true
once_cell.workspace = true
screenshot.workspace = true
spin_sleep.workspace = true
webbrowser.workspace = true
derivative.workspace = true
serde_json.workspace = true
env_logger.workspace = true
mp4-player.workspace = true
downloader.workspace = true
imagedl-rs.workspace = true
musicdl-rs.workspace = true
code-image.workspace = true
mcp-server.workspace = true
ttf-parser.workspace = true
dewatermark.workspace = true
ffmpeg-next.workspace = true
audio-utils.workspace = true
video-utils.workspace = true
musicgen-rs.workspace = true
lfm-vl-onnx.workspace = true
clear-vision.workspace = true
record-audio.workspace = true
image-effect.workspace = true
video-editor.workspace = true
tokio-stream.workspace = true
bili-danmaku.workspace = true
dedup-photos.workspace = true
deconvolution.workspace = true
stem-splitter.workspace = true
deepfilter-rs.workspace = true
native-dialog.workspace = true
video-encoder.workspace = true
platform-dirs.workspace = true
paddle-ocr-rs.workspace = true
screen-capture.workspace = true
image-animation.workspace = true
subtitle-remover.workspace = true
fast_image_resize.workspace = true
background-remover.workspace = true
background-animation.workspace = true
similar-video-segment.workspace = true
sqldb = { workspace = true, optional = true }
image = { workspace = true, optional = true }
qrcode = { workspace = true, optional = true }
uuid = { workspace = true, features = ["v4"] }
tokio = { workspace = true, features = ["full"] }
rustls = { workspace = true, features = ["ring"] }
display-info = { workspace = true, optional = true }
rodio = { workspace = true, features = ["playback"] }
slint = { workspace = true, features = ["backend-qt"] }
tikv-jemallocator = { workspace = true, optional = true }
serde = { workspace = true, features = ["serde_derive"] }
scenesdetect = { workspace = true, features = ["serde"] }
voxcpm-rs = { workspace = true, features = ["all-backends"] }
arboard = { workspace = true, features = ["wayland-data-control"] }
cutil = { workspace = true, features = ["str", "time", "number", "fs", "http"] }

[target.'cfg(target_os = "linux")'.dependencies]
duct.workspace = true

[target.'cfg(any(target_os = "windows", target_os = "linux"))'.dependencies]
fun-ast-nano.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
fun-ast-nano = { workspace = true, features = ["metal"] }

[build-dependencies]
duct.workspace = true
slint-build.workspace = true

[target.'cfg(target_os = "windows")'.build-dependencies]
embed-resource.workspace = true

[features]
default = ["wayland-wlr", "jemalloc"]
windows = ["recorder/windows", "common"]
wayland-wlr = ["recorder/wayland-wlr", "common"]
wayland-portal = ["recorder/wayland-portal", "common"]
common = ["cutil/backup-recover", "database", "dep:image"]
database = ["dep:sqldb"]
jemalloc = ["dep:tikv-jemallocator"]
qrcode = ["dep:image", "dep:qrcode"]
center-window = ["dep:display-info"]

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[[bin]]
path = "src/desktop.rs"
name = "wayshot"
required-features = ["common"]
