mod bg_animation;
mod bg_remover;
mod chapter_summary;
mod clear_vision;
mod code_image;
mod command;
mod common_type;
mod conversion;
mod cutout;
mod dedup_photos;
mod deep_filter;
mod dewatermark;
mod export;
mod filters;
mod font;
mod img_animation;
mod item_preview;
mod library;
mod long_screenshot;
mod mcp;
mod memo;
mod musicgen;
mod ocr;
mod online_search_audio;
mod online_search_image;
mod preview;
mod pure_color_image;
mod record_audio;
mod scene_detect;
mod segment;
mod similar_video_segment;
mod smart_clip;
mod smart_mix;
mod speakers;
mod stem_splitter;
mod subtitle;
mod subtitle_remover;
mod subtitle_translate;
mod terminal;
mod tts;
mod vad;
mod video_helper;

pub mod media_list_common;
pub mod playlist;
pub mod project;
pub mod track;
pub mod transcribe;

pub fn init(ui: &crate::slint_generatedAppWindow::AppWindow) {
    font::init(ui);
    transcribe::app_launch_init(ui);
    project::init(ui);
    export::init(ui);
    library::init(ui);
    playlist::init(ui);
    command::init(ui);
    track::init(ui);
    segment::init(ui);
    filters::init(ui);
    subtitle::init(ui);
    preview::init(ui);
    record_audio::init(ui);
    item_preview::init(ui);
    code_image::init(ui);
    pure_color_image::init(ui);
    tts::init(ui);
    bg_remover::init(ui);
    musicgen::init(ui);
    dewatermark::init(ui);
    cutout::init(ui);
    clear_vision::init(ui);
    ocr::init(ui);
    long_screenshot::init(ui);
    scene_detect::init(ui);
    chapter_summary::init(ui);
    stem_splitter::init(ui);
    deep_filter::init(ui);
    similar_video_segment::init(ui);
    dedup_photos::init(ui);
    subtitle_remover::init(ui);
    subtitle_translate::init(ui);
    speakers::init(ui);
    smart_clip::init(ui);
    smart_mix::init(ui);
    bg_animation::init(ui);
    img_animation::init(ui);
    transcribe::init(ui);
    mcp::init(ui);
    memo::init(ui);
    terminal::init(ui);
    online_search_image::init(ui);
    online_search_audio::init(ui);
}
