import {
    Theme,
    Store,
    Logic,
    Util,
    Icons,
    TranscribeProgressType,
    Transcribe,
    FileType,
} from "../../def.slint";
import {
    CenterLayout,
    IconBtn,
    GainFocus,
    ProgressBar,
    ElevatedBtn,
    PopupActionSetting,
    PopupActionEntry,
    ConfirmDialogSetting,
} from "../../../base/widgets.slint";

export component Header inherits HorizontalLayout {
    out property <bool> is-progressing: !(current-transcribe.progress-type == TranscribeProgressType.None || current-transcribe.progress-type == TranscribeProgressType.Finished || current-transcribe.progress-type == TranscribeProgressType.Cancelled);

    private property <Transcribe> current-transcribe <=> Store.transcribe;

    private property <[PopupActionEntry]> popup-action-entries: [
        {
            icon: Icons.correction-light,
            text: Logic.tr("AI Correction"),
            action: "transcribe-subtitles-correction",
        },
        {
            icon: Icons.remove-light,
            text: Logic.tr("Remove Correction"),
            action: "transcribe-subtitles-remove-correction",
        },
        {
            icon: Icons.to-lowercase-light,
            text: Logic.tr("To Lowercase"),
            action: "transcribe-subtitles-to-lowercase",
        },
        {
            icon: Icons.traditional-to-simple-chinese-light,
            text: Logic.tr("To Simple Chinese"),
            action: "transcribe-subtitles-to-simple-chinese",
        },
        {
            icon: Icons.number-light,
            text: Logic.tr("To Primitive Number"),
            action: "transcribe-subtitles-to-primitive-numbers",
        },
        {
            icon: Icons.separator-light,
            text: Logic.tr("Remove Separator"),
            action: "transcribe-subtitles-remove-separator",
        },
        {
            icon: Icons.overlap-light,
            text: Logic.tr("Adjust Overlap Timestamp"),
            action: "transcribe-subtitles-adjust-overlap-timestamp",
        },
    ];

    callback show-replace-dialog();
    callback show-setting-dialog();

    pure function progress-type-str(ty: TranscribeProgressType) -> string {
        if (ty == TranscribeProgressType.Transcribe) {
            return Logic.tr("transcribing");
        } else if (ty == TranscribeProgressType.CorrectSubtitles) {
            return Logic.tr("correcting subtitles");
        } else if (ty == TranscribeProgressType.Cancelled) {
            return Logic.tr("cancelled");
        } else if (ty == TranscribeProgressType.Finished) {
            return Logic.tr("Finished");
        } else {
            return "";
        }
    }

    pure function progress-type-color(ty: TranscribeProgressType) -> color {
        if (ty == TranscribeProgressType.Cancelled) {
            return Theme.warning-color;
        } else {
            return Theme.thirdly-brand-color;
        }
    }

    spacing: Theme.spacing * 4;
    height: outer-hbox.preferred-height;

    if current-transcribe.progress-type != TranscribeProgressType.None: VerticalLayout {
        alignment: center;
        width: root.width - outer-hbox.preferred-width - parent.spacing;

        HorizontalLayout {
            spacing: Theme.spacing * 4;

            ProgressBar {
                private property <string> progress-text: progress-type-str(current-transcribe.progress-type);

                width: 100%;
                height: 80%;
                clip: true;
                font-weight: Theme.bold-font-weight;
                progress: current-transcribe.progress;
                unfinished-progress-color: progress-type-color(current-transcribe.progress-type);
                unfinished-text: self.progress-text + " " + self.calc-percent(self.progress) + "%";
                finished-text: self.progress-text;
            }
        }
    }

    outer-hbox := HorizontalLayout {
        alignment: end;
        spacing: Theme.spacing * 8;

        if is-progressing: ElevatedBtn {
            icon: Icons.stop-light;
            colorize: Theme.danger-color;
            gain-focus-when-clicked: false;
            is-show-tip: true;
            tip-position: Bottom;
            tip: Logic.tr("cancel");

            clicked => {
                Logic.transcribe-cancel-progress(current-transcribe.progress-type);
            }
        }

        Rectangle {
            height: hbox.preferred-height;
            border-radius: self.height / 2;
            background: Theme.thirdly-background;
            border-width: Theme.default-border-width;
            border-color: Theme.base-border-color;

            hbox := HorizontalLayout {
                spacing: Theme.spacing * 2;
                padding: Theme.padding * 2;
                padding-left: Theme.padding * 4;
                padding-right: Theme.padding * 4;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    IconBtn {
                        is-show-tip: true;
                        tip: Logic.tr("transcribe");
                        icon: Icons.transcribe-light;
                        tip-position: Bottom;
                        hover-color: Store.setting-preference.is-dark ? Theme.secondary-background.darker(50%) : Theme.secondary-background.darker(5%);

                        clicked => {
                            root.show-setting-dialog();
                        }
                    }

                    if current-transcribe.subtitles.length > 0: IconBtn {
                        is-show-tip: true;
                        tip: Logic.tr("refresh");
                        icon: Icons.refresh-light;
                        icon-size: Theme.icon-size * 0.8;
                        tip-position: Bottom;
                        hover-color: Store.setting-preference.is-dark ? Theme.secondary-background.darker(50%) : Theme.secondary-background.darker(5%);

                        clicked => {
                            Logic.transcribe-refresh-subtitles();
                        }
                    }

                    IconBtn {
                        is-show-tip: true;
                        tip: Logic.tr("open file");
                        icon: Icons.open-file-light;
                        icon-size: Theme.icon-size * 0.9;
                        tip-position: Bottom;
                        hover-color: Store.setting-preference.is-dark ? Theme.secondary-background.darker(50%) : Theme.secondary-background.darker(5%);

                        clicked => {
                            Logic.transcribe-new();
                        }
                    }

                    if current-transcribe.subtitles.length > 0: IconBtn {
                        is-show-tip: true;
                        tip: Logic.tr("remove all");
                        icon: Icons.delete-all-light;
                        icon-size: Theme.icon-size * 0.9;
                        tip-position: Bottom;
                        hover-color: Store.setting-preference.is-dark ? Theme.secondary-background.darker(50%) : Theme.secondary-background.darker(5%);

                        clicked => {
                            ConfirmDialogSetting.set(true, Logic.tr("Warning"), Logic.tr("Quit application or not?"), "transcribe-subtitles-remove-all", "");
                        }
                    }

                    if current-transcribe.subtitles.length == 0 && Store.transcribe-can-recovered: IconBtn {
                        is-show-tip: true;
                        tip: Logic.tr("recovery");
                        icon: Icons.recovery-convert-light;
                        icon-size: Theme.icon-size;
                        tip-position: Bottom;
                        hover-color: Store.setting-preference.is-dark ? Theme.secondary-background.darker(50%) : Theme.secondary-background.darker(5%);

                        clicked => {
                            ConfirmDialogSetting.set(true, Logic.tr("Warning"), Logic.tr("Recovery or not?"), "transcribe-subtitles-recovery", "");
                        }
                    }

                    if current-transcribe.subtitles.length > 0: IconBtn {
                        is-show-tip: true;
                        tip: Logic.tr("export subtitle");
                        icon: Icons.export-light;
                        icon-size: Theme.icon-size * 0.9;
                        tip-position: Bottom;
                        hover-color: Store.setting-preference.is-dark ? Theme.secondary-background.darker(50%) : Theme.secondary-background.darker(5%);

                        clicked => {
                            Logic.transcribe-export-subtitles();
                        }
                    }

                    if current-transcribe.subtitles.length > 0: IconBtn {
                        is-show-tip: true;
                        tip: Logic.tr("replace");
                        icon: Icons.replace-light;
                        icon-size: Theme.icon-size * 0.9;
                        tip-position: Bottom;
                        hover-color: Store.setting-preference.is-dark ? Theme.secondary-background.darker(50%) : Theme.secondary-background.darker(5%);

                        clicked => {
                            root.show-replace-dialog();
                        }
                    }
                }

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    IconBtn {
                        icon: Icons.more-v-light;
                        hover-color: Store.setting-preference.is-dark ? Theme.secondary-background.darker(50%) : Theme.secondary-background.darker(5%);

                        clicked => {
                            PopupActionSetting.show(self.absolute-position.x + self.width, self.absolute-position.y, popup-action-entries);
                        }
                    }
                }
            }
        }
    }
}
