import {
    Theme,
    Store,
    Logic,
    Util,
    Icons,
    Transcribe,
    TranscribeProgressType,
    Subtitle,
} from "../../def.slint";
import {
    CenterLayout,
    ConfirmBtn,
    IconBtn,
    GainFocus,
    PopupActionSetting,
    PopupActionEntry,
    ConfirmDialogSetting,
    NoMessageImg,
    Skeleton,
    Label,
    SkeletonType,
    ClickAndEditLabel,
    SoundWaveForm,
} from "../../../base/widgets.slint";
import { Header } from "header.slint";
import { ScrollView } from "std-widgets.slint";
import { SubtitleListItem } from "list-item.slint";

component StartTranscribeField inherits VerticalLayout {
    callback show-setting-dialog();

    CenterLayout {
        NoMessageImg {
            width: root.width;
        }

        HorizontalLayout {
            alignment: center;

            ConfirmBtn {
                icon: Icons.transcribe-light;
                text: Logic.tr("Start transcribe");
                auto-size-vpadding: Theme.padding * 2;

                clicked => {
                    root.show-setting-dialog();
                }
            }
        }
    }
}

component SubtitleListView inherits ScrollView {
    private property current-transcribe <=> Store.transcribe;
    private property <length> list-item-height;
    private property <[Subtitle]> subtitles: Store.transcribe.subtitles;
    private property <bool> is-show-skeleton: (current-transcribe.progress-type == TranscribeProgressType.Transcribe && subtitles.length == 0);
    private property <float> audio-player-progress: Store.transcribe-audio-player-progress;

    function need-scroll() -> bool {
        if (list-item-height <= 0 || current-transcribe.playing-index < 0) {
            return false;
        }
        let pos = ceil(current-transcribe.playing-index / 2) * list-item-height;
        return !(pos > abs(self.viewport-y) && pos < abs(self.viewport-y) + self.height - list-item-height);
    }

    function scroll-to-item() {
        if (list-item-height <= 0 || current-transcribe.playing-index < 0) {
            return;
        }
        root.viewport-y = 0 - clamp(ceil(current-transcribe.playing-index / 2) * list-item-height - list-item-height / 2, 0, root.viewport-height - root.height);
    }

    changed audio-player-progress => {
        Logic.transcribe-subtitles-update-playng-index(audio-player-progress);

        if (current-transcribe.playing-index >= 0 && need-scroll()) {
            scroll-to-item();
        }
    }

    vbox := VerticalLayout {
        spacing: Theme.spacing * 2;

        if is-show-skeleton: Rectangle {
            height: Theme.icon-size * 8;

            Skeleton {
                x: Theme.padding * 2;
                y: Theme.padding * 2;
                width: parent.width - Theme.padding * 4;
                height: parent.height;
                type: SkeletonType.List;
            }
        }

        for entry[index] in subtitles: VerticalLayout {
            spacing: Theme.spacing * 2;

            private property <bool> show-playing-separator: Store.transcribe-audio-player-is-playing && index * 2 + 1 == current-transcribe.playing-index;

            SubtitleListItem {
                index: index;
                entry: entry;
                width: root.width;

                changed height => {
                    self.init();
                }

                init => {
                    root.list-item-height = max(self.height + vbox.spacing, root.list-item-height);
                }
            }

            if show-playing-separator: Rectangle {
                width: root.width;
                height: Theme.padding;
                border-radius: self.height / 2;
                background: Theme.thirdly-brand-color;
                opacity: Util.progress-value(2s);
            }
        }
    }
}

export component Subtitles inherits Rectangle {
    private property current-transcribe <=> Store.transcribe;
    private property <bool> is-transcribing: current-transcribe.progress-type == TranscribeProgressType.Transcribe;
    private property <bool> is-show-no-message: current-transcribe.subtitles.length == 0 && !root.is-transcribing;

    callback show-setting-dialog();

    background: Theme.secondary-background;
    border-radius: Theme.border-radius;

    if !is-show-no-message: VerticalLayout {
        padding: Theme.padding * 2;

        SubtitleListView { }
    }

    if is-show-no-message: StartTranscribeField {
        show-setting-dialog => {
            root.show-setting-dialog();
        }
    }
}
