import {
    Theme,
    Store,
    Logic,
    Util,
    Icons,
    Transcribe,
    TranscribeProgressType,
    Subtitle,
} from "../../def.slint";
import {
    CenterLayout,
    ConfirmBtn,
    IconBtn,
    GainFocus,
    PopupActionSetting,
    PopupActionEntry,
    ConfirmDialogSetting,
    NoMessageImg,
    Skeleton,
    Label,
    SkeletonType,
    ClickAndEditLabel,
    SoundWaveForm,
} from "../../../base/widgets.slint";
import { Header } from "header.slint";
import { ScrollView } from "std-widgets.slint";
import { SubtitleListItem } from "list-item.slint";

component StartTranscribeField inherits VerticalLayout {
    callback show-setting-dialog();

    CenterLayout {
        NoMessageImg {
            width: root.width;
        }

        HorizontalLayout {
            alignment: center;

            ConfirmBtn {
                icon: Icons.transcribe-light;
                text: Logic.tr("Start transcribe");
                auto-size-vpadding: Theme.padding * 2;

                clicked => {
                    root.show-setting-dialog();
                }
            }
        }
    }
}

component SubtitleListView inherits ScrollView {
    private property current-transcribe <=> Store.transcribe;
    private property <[Subtitle]> subtitles: Store.transcribe.subtitles;
    private property <bool> is-show-skeleton: (current-transcribe.progress-type == TranscribeProgressType.Transcribe && subtitles.length == 0);

    VerticalLayout {
        spacing: Theme.spacing * 2;

        if is-show-skeleton: Rectangle {
            height: Theme.icon-size * 8;

            Skeleton {
                x: Theme.padding * 2;
                y: Theme.padding * 2;
                width: parent.width - Theme.padding * 4;
                height: parent.height;
                type: SkeletonType.List;
            }
        }

        for entry[index] in subtitles: SubtitleListItem {
            index: index;
            entry: entry;
            width: root.width;
        }
    }
}

export component Subtitles inherits Rectangle {
    private property current-transcribe <=> Store.transcribe;
    private property <bool> is-transcribing: current-transcribe.progress-type == TranscribeProgressType.Transcribe;
    private property <bool> is-show-no-message: current-transcribe.subtitles.length == 0 && !root.is-transcribing;

    callback show-setting-dialog();

    background: Theme.secondary-background;
    border-radius: Theme.border-radius;

    if !is-show-no-message: VerticalLayout {
        padding: Theme.padding * 2;

        SubtitleListView { }
    }

    if is-show-no-message: StartTranscribeField {
        show-setting-dialog => {
            root.show-setting-dialog();
        }
    }
}
