import {
    Theme,
    Store,
    Logic,
    Util,
    Icons,
    Transcribe,
    FileType,
    SettingTranscribe,
} from "../../def.slint";
import {
    Divider,
    ToolTip,
    PopupAction,
    PopupActionSetting,
    IconBtn,
    ToastStatus,
    FilePicker,
    Banner,
    Label,
    Link,
    TextBtn,
    Blanket,
    ReplaceDialog,
    SimpleAudioControl,
    ConfirmDialogSetting,
} from "../../../base/widgets.slint";
import { Header } from "header.slint";
import { Subtitles } from "subtitles.slint";
import { TranscribeSettingDialog } from "setting.slint";

export component TranscribePanel inherits Rectangle {
    private property <Transcribe> current-transcribe <=> Store.transcribe;
    private property <SettingTranscribe> cache-setting <=> Store.transcribe-setting-cache;
    private property <bool> is-show-replace-dialog;
    private property <bool> is-show-file-picker: current-transcribe.file-path.is-empty;

    private property <bool> is-show-import-banner: !Store.transcribe.is-file-exist;
    private property <bool> is-show-setting-dialog;

    init => {
        Logic.transcribe-init();
        Logic.transcribe-audio-player-init();

        if (!current-transcribe.is-file-exist) {
            ConfirmDialogSetting.set(true, Logic.tr("Warning"), Logic.tr("No found media file. Import file or not?"), "transcribe-import-file", "");
        }
    }

    if is-show-file-picker: FilePicker {
        icon: Icons.media-light;
        title: Logic.tr("Support video and audio files");
        sub-title: "e.g. mp4, mkv, mp3, wav...";

        select-file => {
            Logic.transcribe-new();
        }
    }

    if !is-show-file-picker: VerticalLayout {
        padding: Theme.padding * 2;
        spacing: Theme.spacing * 2;

        header := Header {
            show-replace-dialog => {
                root.is-show-replace-dialog = true;
            }

            show-setting-dialog => {
                root.is-show-setting-dialog = true;
            }
        }

        HorizontalLayout {
            padding-top: Theme.spacing * 2;

            Subtitles {
                is-progressing: header.is-progressing;

                show-setting-dialog => {
                    root.is-show-setting-dialog = true;
                }
            }
        }

        SimpleAudioControl {
            play => {
            }

            stop => {
            }

            sound-changed(sound) => {
            }
            progress-changed => {
            }
            progress-release => {
            }
            progress-pressed => {
            }
        }
    }

    if is-show-replace-dialog: ReplaceDialog {
        escape => {
            is-show-replace-dialog = false;
        }
    }

    if is-show-setting-dialog: Blanket {
        clicked => {
            is-show-setting-dialog = false;
        }
    }

    if is-show-setting-dialog: TranscribeSettingDialog {
        width: Math.min(Theme.dialog-max-width, root.width * 0.8);

        escape => {
            is-show-setting-dialog = false;
        }
    }
}
