[package]
name = "video-utils"
license.workspace = true
edition.workspace = true
version.workspace = true
readme.workspace = true
authors.workspace = true
keywords.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
log.workspace = true
image.workspace = true
chrono.workspace = true
thiserror.workspace = true
fast_image_resize.workspace = true
unicode-segmentation.workspace = true
yuv = { workspace = true, optional = true }
ffmpeg-next = { workspace = true, optional = true }
chinese-number = { workspace = true, features = ["chinese-to-number"] }

[features]
default = []
ffmpeg = ["dep:ffmpeg-next", "dep:yuv"]

[dev-dependencies]
