import {
    Theme,
    Logic,
    Icons,
    Store,
} from "../../../../../def.slint";
import {
    Label,
    SettingDetailLabel,
    SettingDetailInnerVbox,
    LineInput,
} from "../../../../../../base/widgets.slint";
import {
    BorderRadiusDetail,
} from "../../../filter.slint";

export component BorderRadius inherits Rectangle {
    in-out property <BorderRadiusDetail> config;

    callback apply(config: BorderRadiusDetail);

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Border radius");
        }

        LineInput {
            private property <bool> unsaved;
            input-type: number;
            text: config.radius;
            border-color: self.unsaved ? Theme.danger-color : (self.has-focus ? Theme.thirdly-brand-color : Theme.is-dark ? Theme.base-border-color.brighter(20%) : Theme.base-border-color.darker(10%));

            changed has-focus => {
                if (!self.has-focus) {
                    Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                }
            }

            edited => {
                unsaved = true;
            }

            accepted => {
                unsaved = false;
                config.radius = round(self.text.to-float());
                apply(config);
            }
        }
    }
}
