import {
    Theme,
    Logic,
    Icons,
    Store,
} from "../../../../../def.slint";
import {
    Label,
    SettingDetailInnerVbox,
    SettingDetailLabel,
    LineInput,
} from "../../../../../../base/widgets.slint";
import {
    VEFilter,
    SegmentFilter,
    FontSizeDetail,
} from "../../../filter.slint";

export component FontSize inherits SettingDetailInnerVbox {
    in-out property <FontSizeDetail> config;
    callback apply(config: FontSizeDetail);

    SettingDetailLabel {
        text: Logic.tr("Font size");
    }

    LineInput {
        private property <bool> unsaved;
        input-type: number;
        text: config.font-size;
        border-color: self.unsaved ? Theme.danger-color : (self.has-focus ? Theme.thirdly-brand-color : Theme.is-dark ? Theme.base-border-color.brighter(20%) : Theme.base-border-color.darker(10%));

        changed has-focus => {
            if (!self.has-focus) {
                Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
            }
        }

        edited => {
            unsaved = true;
        }

        accepted => {
            unsaved = false;
            config.font-size = round(self.text.to-float());
            apply(config);
        }
    }
}
