import {
    Theme,
    Logic,
    Store,
} from "../../../../../def.slint";
import {
    SettingDetailInner,
    SettingDetailInnerVbox,
    SettingDetailLabel,
    LineInput,
} from "../../../../../../base/widgets.slint";
import {
    VEFilter,
    SegmentFilter,
    NoiseGateDetail,
} from "../../../filter.slint";

export component NoiseGate inherits Rectangle {
    in-out property <int> index: -1;
    in-out property <SegmentFilter> selected-filter;
    in-out property <NoiseGateDetail> config: VEFilter.from-noise-gate-json(selected-filter.detail);

    SettingDetailInner {
        interactive: false;
        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Threshold (dB)");
                enabled: selected-filter.enabled;
            }

            LineInput {
                enabled: selected-filter.enabled;
                input-type: InputType.decimal;
                text: config.threshold.to-fixed(2);
                border-color: self.has-focus ? Theme.thirdly-brand-color : Theme.is-dark ? Theme.base-border-color.brighter(20%) : Theme.base-border-color.darker(10%);

                changed has-focus => {
                    if (!self.has-focus) {
                        Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                    }
                }

                accepted => {
                    config.threshold = self.text.to-float();
                    VEFilter.modify-noise-gate-filter(index, config);
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Ratio");
                enabled: selected-filter.enabled;
            }

            LineInput {
                enabled: selected-filter.enabled;
                input-type: InputType.decimal;
                text: config.ratio.to-fixed(2);
                border-color: self.has-focus ? Theme.thirdly-brand-color : Theme.is-dark ? Theme.base-border-color.brighter(20%) : Theme.base-border-color.darker(10%);

                changed has-focus => {
                    if (!self.has-focus) {
                        Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                    }
                }

                accepted => {
                    config.ratio = self.text.to-float();
                    VEFilter.modify-noise-gate-filter(index, config);
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Attack (ms)");
                enabled: selected-filter.enabled;
            }

            LineInput {
                enabled: selected-filter.enabled;
                input-type: InputType.decimal;
                text: config.attack.to-fixed(2);
                border-color: self.has-focus ? Theme.thirdly-brand-color : Theme.is-dark ? Theme.base-border-color.brighter(20%) : Theme.base-border-color.darker(10%);

                changed has-focus => {
                    if (!self.has-focus) {
                        Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                    }
                }

                accepted => {
                    config.attack = self.text.to-float();
                    VEFilter.modify-noise-gate-filter(index, config);
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Hold (ms)");
                enabled: selected-filter.enabled;
            }

            LineInput {
                enabled: selected-filter.enabled;
                input-type: InputType.decimal;
                text: config.hold.to-fixed(2);
                border-color: self.has-focus ? Theme.thirdly-brand-color : Theme.is-dark ? Theme.base-border-color.brighter(20%) : Theme.base-border-color.darker(10%);

                changed has-focus => {
                    if (!self.has-focus) {
                        Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                    }
                }

                accepted => {
                    config.hold = self.text.to-float();
                    VEFilter.modify-noise-gate-filter(index, config);
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Release (ms)");
                enabled: selected-filter.enabled;
            }

            LineInput {
                enabled: selected-filter.enabled;
                input-type: InputType.decimal;
                text: config.release.to-fixed(2);
                border-color: self.has-focus ? Theme.thirdly-brand-color : Theme.is-dark ? Theme.base-border-color.brighter(20%) : Theme.base-border-color.darker(10%);

                changed has-focus => {
                    if (!self.has-focus) {
                        Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                    }
                }

                accepted => {
                    config.release = self.text.to-float();
                    VEFilter.modify-noise-gate-filter(index, config);
                }
            }
        }

        VerticalLayout { }
    }
}

