const TR_FILE_CONTENT: &str = include_str!("../wayshot/src/logic/tr.rs");

fn main() {
    let clean_contents = remove_codes(TR_FILE_CONTENT);
    let clean_contents = format!("// Auto-generated by build.rs.\n{}", clean_contents);
    std::fs::write("src/tr.rs", clean_contents).unwrap();
}

fn remove_codes(input: &str) -> String {
    input
        .replace(
            r#"let lang = crate::config::all().preference.language.clone();"#,
            "",
        )
        .replace("tr(text: &str)", "tr(text: &str, lang: String)")
        .to_string()
}
