import {
    Store,
    Logic,
    Theme,
    Icons,
    Util,
} from "../../../../def.slint";
import {
    Label,
    LineInput,
    SettingDetailInnerVbox,
    SettingDetailLabel,
} from "../../../../../base/widgets.slint";

export component CrossLineParams inherits VerticalLayout {
    spacing: Theme.spacing * 4;

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Lines Count");
        }

        LineInput {
            input-type: InputType.number;
            text: Store.video-editor-bg-animation-config.cross-line.lines-num;

            accepted => {
                let input-value = round(self.text.to-float());
                let value = input-value <= 0 ? 16 : input-value;
                Store.video-editor-bg-animation-config.cross-line.lines-num = value;
                self.text = value;
            }
        }
    }

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Line Width");
        }

        LineInput {
            input-type: InputType.decimal;
            text: Store.video-editor-bg-animation-config.cross-line.line-width.to-fixed(1);

            accepted => {
                Store.video-editor-bg-animation-config.cross-line.line-width = self.text.to-float();
            }
        }
    }

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Point Radius");
        }

        LineInput {
            input-type: InputType.decimal;
            text: Store.video-editor-bg-animation-config.cross-line.point-radius.to-fixed(1);

            accepted => {
                Store.video-editor-bg-animation-config.cross-line.point-radius = self.text.to-float();
            }
        }
    }

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Speed Range");
        }

        HorizontalLayout {
            spacing: Theme.spacing * 2;

            LineInput {
                input-type: InputType.decimal;
                text: Store.video-editor-bg-animation-config.cross-line.speed-min.to-fixed(2);

                accepted => {
                    Store.video-editor-bg-animation-config.cross-line.speed-min = self.text.to-float();
                }
            }

            Label {
                text: "-";
            }

            LineInput {
                input-type: InputType.decimal;
                text: Store.video-editor-bg-animation-config.cross-line.speed-max.to-fixed(2);

                accepted => {
                    Store.video-editor-bg-animation-config.cross-line.speed-max = self.text.to-float();
                }
            }
        }
    }

    SettingDetailInnerVbox {
        private property <bool> color-picker-confirmed-flag: Store.video-editor-color-picker-confirmed-flag;
        private property <int> color-picker-id;

        changed color-picker-confirmed-flag => {
            if (color-picker-id != Store.video-editor-color-picker-id) {
                return;
            }
            let c = Store.video-editor-color-picker-color;
            Store.video-editor-bg-animation-config.cross-line.bg-color-r = c.red;
            Store.video-editor-bg-animation-config.cross-line.bg-color-g = c.green;
            Store.video-editor-bg-animation-config.cross-line.bg-color-b = c.blue;
        }

        SettingDetailLabel {
            text: Logic.tr("Background Color");
        }

        LineInput {
            read-only: true;
            is-show-icon: true;
            text: Util.color-picker-str(
                Store.video-editor-bg-animation-config.cross-line.bg-color-r,
                Store.video-editor-bg-animation-config.cross-line.bg-color-g,
                Store.video-editor-bg-animation-config.cross-line.bg-color-b,
                255);
            is-show-color-block: true;
            color-block-color: Util.color-picker-hex-color(self.text);
            icon: Icons.color-picker-light;

            clicked => {
                Store.video-editor-color-picker-id += 1;
                color-picker-id = Store.video-editor-color-picker-id;
                Store.video-editor-color-picker-color = Util.color-picker-hex-color(self.text);
                Store.video-editor-color-picker-toggle-flag = !Store.video-editor-color-picker-toggle-flag;
            }
        }
    }
}
