import {
    Store,
    Logic,
    Theme,
    Icons,
    Util,
} from "../../../../def.slint";
import {
    LineInput,
    SettingDetailInnerVbox,
    SettingDetailLabel,
} from "../../../../../base/widgets.slint";

export component GridParams inherits VerticalLayout {
    spacing: Theme.spacing * 4;

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Rows");
        }

        LineInput {
            input-type: InputType.number;
            text: Store.video-editor-bg-animation-config.grid.rows;

            accepted => {
                let input-value = round(self.text.to-float());
                let value = input-value <= 0 ? 20 : input-value;
                Store.video-editor-bg-animation-config.grid.rows = value;
                self.text = value;
            }
        }
    }

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Columns");
        }

        LineInput {
            input-type: InputType.number;
            text: Store.video-editor-bg-animation-config.grid.cols;

            accepted => {
                let input-value = round(self.text.to-float());
                let value = input-value <= 0 ? 20 : input-value;
                Store.video-editor-bg-animation-config.grid.cols = value;
                self.text = value;
            }
        }
    }

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Frequency");
        }

        LineInput {
            input-type: InputType.decimal;
            text: Store.video-editor-bg-animation-config.grid.frequency.to-fixed(2);

            accepted => {
                Store.video-editor-bg-animation-config.grid.frequency = self.text.to-float();
            }
        }
    }

    // Line Color
    SettingDetailInnerVbox {
        private property <bool> color-picker-confirmed-flag: Store.video-editor-color-picker-confirmed-flag;
        private property <int> color-picker-id;

        changed color-picker-confirmed-flag => {
            if (color-picker-id != Store.video-editor-color-picker-id) {
                return;
            }
            let c = Store.video-editor-color-picker-color;
            Store.video-editor-bg-animation-config.grid.line-color-r = c.red;
            Store.video-editor-bg-animation-config.grid.line-color-g = c.green;
            Store.video-editor-bg-animation-config.grid.line-color-b = c.blue;
            Store.video-editor-bg-animation-config.grid.line-color-a = c.alpha;
        }

        SettingDetailLabel {
            text: Logic.tr("Line Color");
        }

        LineInput {
            read-only: true;
            is-show-icon: true;
            text: Util.color-picker-str(
                Store.video-editor-bg-animation-config.grid.line-color-r,
                Store.video-editor-bg-animation-config.grid.line-color-g,
                Store.video-editor-bg-animation-config.grid.line-color-b,
                Store.video-editor-bg-animation-config.grid.line-color-a);
            is-show-color-block: true;
            color-block-color: Util.color-picker-hex-color(self.text);
            icon: Icons.color-picker-light;

            clicked => {
                Store.video-editor-color-picker-id += 1;
                color-picker-id = Store.video-editor-color-picker-id;
                Store.video-editor-color-picker-color = Util.color-picker-hex-color(self.text);
                Store.video-editor-color-picker-toggle-flag = !Store.video-editor-color-picker-toggle-flag;
            }
        }
    }

    SettingDetailInnerVbox {
        private property <bool> color-picker-confirmed-flag: Store.video-editor-color-picker-confirmed-flag;
        private property <int> color-picker-id;

        changed color-picker-confirmed-flag => {
            if (color-picker-id != Store.video-editor-color-picker-id) {
                return;
            }
            let c = Store.video-editor-color-picker-color;
            Store.video-editor-bg-animation-config.grid.node-color-r = c.red;
            Store.video-editor-bg-animation-config.grid.node-color-g = c.green;
            Store.video-editor-bg-animation-config.grid.node-color-b = c.blue;
            Store.video-editor-bg-animation-config.grid.node-color-a = c.alpha;
        }

        SettingDetailLabel {
            text: Logic.tr("Node Color");
        }

        LineInput {
            read-only: true;
            is-show-icon: true;
            text: Util.color-picker-str(
                Store.video-editor-bg-animation-config.grid.node-color-r,
                Store.video-editor-bg-animation-config.grid.node-color-g,
                Store.video-editor-bg-animation-config.grid.node-color-b,
                Store.video-editor-bg-animation-config.grid.node-color-a);
            is-show-color-block: true;
            color-block-color: Util.color-picker-hex-color(self.text);
            icon: Icons.color-picker-light;

            clicked => {
                Store.video-editor-color-picker-id += 1;
                color-picker-id = Store.video-editor-color-picker-id;
                Store.video-editor-color-picker-color = Util.color-picker-hex-color(self.text);
                Store.video-editor-color-picker-toggle-flag = !Store.video-editor-color-picker-toggle-flag;
            }
        }
    }

    SettingDetailInnerVbox {
        private property <bool> color-picker-confirmed-flag: Store.video-editor-color-picker-confirmed-flag;
        private property <int> color-picker-id;

        changed color-picker-confirmed-flag => {
            if (color-picker-id != Store.video-editor-color-picker-id) {
                return;
            }
            let c = Store.video-editor-color-picker-color;
            Store.video-editor-bg-animation-config.grid.bg-color-r = c.red;
            Store.video-editor-bg-animation-config.grid.bg-color-g = c.green;
            Store.video-editor-bg-animation-config.grid.bg-color-b = c.blue;
        }

        SettingDetailLabel {
            text: Logic.tr("Background Color");
        }

        LineInput {
            read-only: true;
            is-show-icon: true;
            text: Util.color-picker-str(
                Store.video-editor-bg-animation-config.grid.bg-color-r,
                Store.video-editor-bg-animation-config.grid.bg-color-g,
                Store.video-editor-bg-animation-config.grid.bg-color-b,
                255);
            is-show-color-block: true;
            color-block-color: Util.color-picker-hex-color(self.text);
            icon: Icons.color-picker-light;

            clicked => {
                Store.video-editor-color-picker-id += 1;
                color-picker-id = Store.video-editor-color-picker-id;
                Store.video-editor-color-picker-color = Util.color-picker-hex-color(self.text);
                Store.video-editor-color-picker-toggle-flag = !Store.video-editor-color-picker-toggle-flag;
            }
        }
    }
}

