import {
    Store,
    Logic,
    Theme,
    Icons,
    Util,
} from "../../../../def.slint";
import {
    Label,
    LineInput,
    SettingDetailInnerVbox,
    SettingDetailLabel,
} from "../../../../../base/widgets.slint";

export component TriangleParams inherits VerticalLayout {
    spacing: Theme.spacing * 4;

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Particle Count");
        }

        LineInput {
            input-type: InputType.number;
            text: Store.video-editor-bg-animation-config.triangle.particle-count;

            accepted => {
                let input-value = round(self.text.to-float());
                let value = input-value <= 0 ? 80 : input-value;
                Store.video-editor-bg-animation-config.triangle.particle-count = value;
                self.text = value;
            }
        }
    }

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Point Variation X");
        }

        LineInput {
            input-type: InputType.decimal;
            text: Store.video-editor-bg-animation-config.triangle.point-variation-x.to-fixed(1);

            accepted => {
                Store.video-editor-bg-animation-config.triangle.point-variation-x = self.text.to-float();
            }
        }
    }

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Point Variation Y");
        }

        LineInput {
            input-type: InputType.decimal;
            text: Store.video-editor-bg-animation-config.triangle.point-variation-y.to-fixed(1);

            accepted => {
                Store.video-editor-bg-animation-config.triangle.point-variation-y = self.text.to-float();
            }
        }
    }

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Animation Speed");
        }

        LineInput {
            input-type: InputType.decimal;
            text: Store.video-editor-bg-animation-config.triangle.point-animation-speed.to-fixed(1);

            accepted => {
                Store.video-editor-bg-animation-config.triangle.point-animation-speed = self.text.to-float();
            }
        }
    }

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Triangle Size");
        }

        LineInput {
            input-type: InputType.decimal;
            text: Store.video-editor-bg-animation-config.triangle.triangle-size.to-fixed(1);

            accepted => {
                let value = self.text.to-float();
                Store.video-editor-bg-animation-config.triangle.triangle-size = value <= 0.0 ? 130.0 : value;
            }
        }
    }

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Bleed");
        }

        LineInput {
            input-type: InputType.decimal;
            text: Store.video-editor-bg-animation-config.triangle.bleed.to-fixed(1);

            accepted => {
                Store.video-editor-bg-animation-config.triangle.bleed = self.text.to-float();
            }
        }
    }

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Noise");
        }

        LineInput {
            input-type: InputType.decimal;
            text: Store.video-editor-bg-animation-config.triangle.noise.to-fixed(1);

            accepted => {
                Store.video-editor-bg-animation-config.triangle.noise = self.text.to-float();
            }
        }
    }

    SettingDetailInnerVbox {
        SettingDetailLabel {
            text: Logic.tr("Stroke Width");
        }

        LineInput {
            input-type: InputType.decimal;
            text: Store.video-editor-bg-animation-config.triangle.stroke-width.to-fixed(1);

            accepted => {
                Store.video-editor-bg-animation-config.triangle.stroke-width = self.text.to-float();
            }
        }
    }

    SettingDetailInnerVbox {
        private property <bool> color-picker-confirmed-flag: Store.video-editor-color-picker-confirmed-flag;
        private property <int> color-picker-id;

        changed color-picker-confirmed-flag => {
            if (color-picker-id != Store.video-editor-color-picker-id) {
                return;
            }
            let c = Store.video-editor-color-picker-color;
            Store.video-editor-bg-animation-config.triangle.stroke-color-r = c.red;
            Store.video-editor-bg-animation-config.triangle.stroke-color-g = c.green;
            Store.video-editor-bg-animation-config.triangle.stroke-color-b = c.blue;
        }

        SettingDetailLabel {
            text: Logic.tr("Stroke Color");
        }

        LineInput {
            read-only: true;
            is-show-icon: true;
            text: Util.color-picker-str(
                Store.video-editor-bg-animation-config.triangle.stroke-color-r,
                Store.video-editor-bg-animation-config.triangle.stroke-color-g,
                Store.video-editor-bg-animation-config.triangle.stroke-color-b,
                Store.video-editor-bg-animation-config.triangle.stroke-color-a);
            is-show-color-block: true;
            color-block-color: Util.color-picker-hex-color(self.text);
            icon: Icons.color-picker-light;

            clicked => {
                Store.video-editor-color-picker-id += 1;
                color-picker-id = Store.video-editor-color-picker-id;
                Store.video-editor-color-picker-color = Util.color-picker-hex-color(self.text);
                Store.video-editor-color-picker-toggle-flag = !Store.video-editor-color-picker-toggle-flag;
            }
        }
    }

    SettingDetailInnerVbox {
        private property <bool> color-picker-confirmed-flag: Store.video-editor-color-picker-confirmed-flag;
        private property <int> color-picker-id;

        changed color-picker-confirmed-flag => {
            if (color-picker-id != Store.video-editor-color-picker-id) {
                return;
            }
            let c = Store.video-editor-color-picker-color;
            Store.video-editor-bg-animation-config.triangle.color1-r = c.red;
            Store.video-editor-bg-animation-config.triangle.color1-g = c.green;
            Store.video-editor-bg-animation-config.triangle.color1-b = c.blue;
        }

        SettingDetailLabel {
            text: Logic.tr("Color 1");
        }

        LineInput {
            read-only: true;
            is-show-icon: true;
            text: Util.color-picker-str(
                Store.video-editor-bg-animation-config.triangle.color1-r,
                Store.video-editor-bg-animation-config.triangle.color1-g,
                Store.video-editor-bg-animation-config.triangle.color1-b,
                255);
            is-show-color-block: true;
            color-block-color: Util.color-picker-hex-color(self.text);
            icon: Icons.color-picker-light;

            clicked => {
                Store.video-editor-color-picker-id += 1;
                color-picker-id = Store.video-editor-color-picker-id;
                Store.video-editor-color-picker-color = Util.color-picker-hex-color(self.text);
                Store.video-editor-color-picker-toggle-flag = !Store.video-editor-color-picker-toggle-flag;
            }
        }
    }

    SettingDetailInnerVbox {
        private property <bool> color-picker-confirmed-flag: Store.video-editor-color-picker-confirmed-flag;
        private property <int> color-picker-id;

        changed color-picker-confirmed-flag => {
            if (color-picker-id != Store.video-editor-color-picker-id) {
                return;
            }
            let c = Store.video-editor-color-picker-color;
            Store.video-editor-bg-animation-config.triangle.color2-r = c.red;
            Store.video-editor-bg-animation-config.triangle.color2-g = c.green;
            Store.video-editor-bg-animation-config.triangle.color2-b = c.blue;
        }

        SettingDetailLabel {
            text: Logic.tr("Color 2");
        }

        LineInput {
            read-only: true;
            is-show-icon: true;
            text: Util.color-picker-str(
                Store.video-editor-bg-animation-config.triangle.color2-r,
                Store.video-editor-bg-animation-config.triangle.color2-g,
                Store.video-editor-bg-animation-config.triangle.color2-b,
                255);
            is-show-color-block: true;
            color-block-color: Util.color-picker-hex-color(self.text);
            icon: Icons.color-picker-light;

            clicked => {
                Store.video-editor-color-picker-id += 1;
                color-picker-id = Store.video-editor-color-picker-id;
                Store.video-editor-color-picker-color = Util.color-picker-hex-color(self.text);
                Store.video-editor-color-picker-toggle-flag = !Store.video-editor-color-picker-toggle-flag;
            }
        }
    }

    SettingDetailInnerVbox {
        private property <bool> color-picker-confirmed-flag: Store.video-editor-color-picker-confirmed-flag;
        private property <int> color-picker-id;

        changed color-picker-confirmed-flag => {
            if (color-picker-id != Store.video-editor-color-picker-id) {
                return;
            }
            let c = Store.video-editor-color-picker-color;
            Store.video-editor-bg-animation-config.triangle.bg-color-r = c.red;
            Store.video-editor-bg-animation-config.triangle.bg-color-g = c.green;
            Store.video-editor-bg-animation-config.triangle.bg-color-b = c.blue;
        }

        SettingDetailLabel {
            text: Logic.tr("Background Color");
        }

        LineInput {
            read-only: true;
            is-show-icon: true;
            text: Util.color-picker-str(
                Store.video-editor-bg-animation-config.triangle.bg-color-r,
                Store.video-editor-bg-animation-config.triangle.bg-color-g,
                Store.video-editor-bg-animation-config.triangle.bg-color-b,
                255);
            is-show-color-block: true;
            color-block-color: Util.color-picker-hex-color(self.text);
            icon: Icons.color-picker-light;

            clicked => {
                Store.video-editor-color-picker-id += 1;
                color-picker-id = Store.video-editor-color-picker-id;
                Store.video-editor-color-picker-color = Util.color-picker-hex-color(self.text);
                Store.video-editor-color-picker-toggle-flag = !Store.video-editor-color-picker-toggle-flag;
            }
        }
    }
}
