# 64 bit MSVC
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:33554432"]

# 64 bit Mingw
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=/STACK:33554432"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,-z,stack-size=33554432"]
