import {
    Theme,
    Logic,
    Store,
} from "../../../../../def.slint";
import {
    Slider,
    CheckBtn,
    SettingDetailInner,
    SettingDetailInnerVbox,
    SettingDetailLabel,
    LineInput,
} from "../../../../../../base/widgets.slint";
import {
    VEFilter,
    SegmentFilter,
    CircleMaskDetail,
} from "../../../filter.slint";
import { KeyframeButton } from "../keyframe-btn.slint";
import {
    SettingDetailSwitch,
} from "../../../../../../base/setting-detail.slint";
import { Icons } from "../../../../../../base/theme.slint";
import { ClickAndEditLabel } from "../../../../../../base/line-input.slint";

export component CircleMask inherits Rectangle {
    in-out property <int> index: -1;
    in-out property <SegmentFilter> selected-filter;
    in-out property <CircleMaskDetail> config: VEFilter.from-circle-mask-json(selected-filter.detail);
    in-out property toggle-keyframe-flag <=> VEFilter.toggle-keyframe-flag;

    callback apply(index: int, config: CircleMaskDetail);

    changed selected-filter => {
        if (selected-filter.name == "circle mask") {
            self.config = VEFilter.from-circle-mask-json(selected-filter.detail);
            center-x-sl.value = self.config.center-x;
            center-y-sl.value = self.config.center-y;
            radius-li.text = self.config.radius;
            feather-sl.value = self.config.feather;
            opacity-sl.value = self.config.opacity;
        }
    }

    SettingDetailInner {
        interactive: false;

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Center X");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        center-x-sl := Slider {
                            minimum: 0.0;
                            maximum: 1.0;
                            value: config.center-x;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.center-x = value;
                            }

                            released(value) => {
                                config.center-x = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 3;
                        text: config.center-x.to-fixed(2);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.center-x = text.to-float().clamp(0, 1);
                            center-x-sl.value = config.center-x;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "center_x", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "center_x", VEFilter.make-float-value(config.center-x));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Center Y");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        center-y-sl := Slider {
                            minimum: 0.0;
                            maximum: 1.0;
                            value: config.center-y;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.center-y = value;
                            }

                            released(value) => {
                                config.center-y = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 3;
                        text: config.center-y.to-fixed(2);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.center-y = text.to-float().clamp(0, 1);
                            center-y-sl.value = config.center-y;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "center_y", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "center_y", VEFilter.make-float-value(config.center-y));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Radius");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                radius-li := LineInput {
                    enabled: selected-filter.enabled;
                    input-type: InputType.number;
                    text: config.radius;

                    changed has-focus => {
                        if (!self.has-focus) {
                            Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                        }
                    }

                    accepted => {
                        config.radius = self.text.to-float().clamp(0, 5000);
                        apply(index, config);
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "radius", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "radius", VEFilter.make-float-value(config.radius));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Feather");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        feather-sl := Slider {
                            minimum: 0.0;
                            maximum: 1.0;
                            value: config.feather;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.feather = value;
                            }

                            released(value) => {
                                config.feather = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 3;
                        text: config.feather.to-fixed(2);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.feather = text.to-float().clamp(0, 1);
                            feather-sl.value = config.feather;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "feather", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "feather", VEFilter.make-float-value(config.feather));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Opacity");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        opacity-sl := Slider {
                            minimum: 0.0;
                            maximum: 1.0;
                            value: config.opacity;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.opacity = value;
                            }

                            released(value) => {
                                config.opacity = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 3;
                        text: config.opacity.to-fixed(2);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.opacity = text.to-float().clamp(0, 1);
                            opacity-sl.value = config.opacity;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "opacity", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "opacity", VEFilter.make-float-value(config.opacity));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailSwitch {
            enabled: selected-filter.enabled;
            text: Logic.tr("Flip");
            checked: config.flip;
            icon: Icons.invert-light;
            icon-size: Theme.icon-size * 0.8;
            background: Theme.thirdly-background;

            toggled => {
                config.flip = self.checked;
                apply(index, config);
            }
        }

        VerticalLayout { }
    }
}
