import {
    Theme,
    Logic,
    Store,
    KeyframeValueType,
    KeyframeValue,
} from "../../../../../def.slint";
import {
    ClickAndEditLabel,
    LineInput,
    Slider,
    SettingDetailInner,
    SettingDetailInnerVbox,
    SettingDetailLabel,
} from "../../../../../../base/widgets.slint";
import {
    VEFilter,
    SegmentFilter,
    DirectionalBlurDetail,
} from "../../../filter.slint";
import { KeyframeButton } from "../keyframe-btn.slint";

export component DirectionalBlur inherits Rectangle {
    in-out property <int> index: -1;
    in-out property <SegmentFilter> selected-filter;
    in-out property <DirectionalBlurDetail> config: VEFilter.from-directional-blur-json(selected-filter.detail);
    in-out property toggle-keyframe-flag <=> VEFilter.toggle-keyframe-flag;

    callback apply(index: int, config: DirectionalBlurDetail);

    changed selected-filter => {
        if (selected-filter.name == "directional blur") {
            self.config = VEFilter.from-directional-blur-json(selected-filter.detail);
            angle-sl.value = self.config.angle;
            length-sl.value = self.config.length;
            spread-sl.value = self.config.spread;
        }
    }

    SettingDetailInner {
        interactive: false;

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Angle");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        angle-sl := Slider {
                            minimum: 0.0;
                            maximum: 360.0;
                            value: config.angle;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.angle = value;
                            }

                            released(value) => {
                                config.angle = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 3;
                        text: config.angle.to-fixed(1);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.angle = text.to-float().clamp(0, 360);
                            angle-sl.value = config.angle;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "angle", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "angle", VEFilter.make-float-value(config.angle));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Length");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;
                        length-sl := Slider {
                            minimum: 0.0;
                            maximum: 100.0;
                            value: config.length;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.length = value;
                            }

                            released(value) => {
                                config.length = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 3;
                        text: config.length.to-fixed(1);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.length = text.to-float().clamp(0, 100);
                            length-sl.value = config.length;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;
                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "length", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "length", VEFilter.make-float-value(config.length));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Spread");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;
                        spread-sl := Slider {
                            minimum: 0.0;
                            maximum: 1.0;
                            value: config.spread;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.spread = value;
                            }

                            released(value) => {
                                config.spread = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 3;
                        text: config.spread.to-fixed(2);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.spread = text.to-float().clamp(0, 1);
                            spread-sl.value = config.spread;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;
                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "spread", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "spread", VEFilter.make-float-value(config.spread));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        VerticalLayout { }
    }
}

