import {
    Theme,
    Logic,
    Icons,
    Util,
    Store,
    KeyframeValueType,
    KeyframeValue,
} from "../../../../../def.slint";
import {
    LineInput,
    Slider,
    SettingDetailInner,
    SettingDetailInnerVbox,
    SettingDetailLabel,
    SettingDetailSwitch,
    ClickAndEditLabel,
} from "../../../../../../base/widgets.slint";
import {
    VEFilter,
    SegmentFilter,
    EdgeDetectDetail,
} from "../../../filter.slint";
import { KeyframeButton } from "../keyframe-btn.slint";
import { Icons } from "../../../../../../base/icon.slint";

export component EdgeDetect inherits Rectangle {
    in-out property <int> index: -1;
    in-out property <SegmentFilter> selected-filter;
    in-out property <EdgeDetectDetail> config: VEFilter.from-edge-detect-json(selected-filter.detail);
    in-out property toggle-keyframe-flag <=> VEFilter.toggle-keyframe-flag;
    in-out property <bool> color-picker-confirmed-flag: Store.video-editor-color-picker-confirmed-flag;
    private property <int> video-editor-color-picker-id-edge;
    private property <int> video-editor-color-picker-id-bg;

    changed color-picker-confirmed-flag => {
        if (video-editor-color-picker-id-edge != Store.video-editor-color-picker-id) {
            if (video-editor-color-picker-id-bg != Store.video-editor-color-picker-id) {
                return;
            }
        }
        let c = Store.video-editor-color-picker-color;
        if (video-editor-color-picker-id-edge == Store.video-editor-color-picker-id) {
            config.edge-color-r = c.red;
            config.edge-color-g = c.green;
            config.edge-color-b = c.blue;
            config.edge-color-a = c.alpha;
        }
        if (video-editor-color-picker-id-bg == Store.video-editor-color-picker-id) {
            config.background-color-r = c.red;
            config.background-color-g = c.green;
            config.background-color-b = c.blue;
            config.background-color-a = c.alpha;
        }
        apply(index, config);
    }

    callback apply(index: int, config: EdgeDetectDetail);

    changed selected-filter => {
        if (selected-filter.name == "edge detect") {
            self.config = VEFilter.from-edge-detect-json(selected-filter.detail);
            threshold-sl.value = self.config.threshold;
            strength-sl.value = self.config.strength;
        }
    }

    SettingDetailInner {
        interactive: false;

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Threshold");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        threshold-sl := Slider {
                            minimum: 0.0;
                            maximum: 255.0;
                            value: config.threshold;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.threshold = value;
                            }

                            released(value) => {
                                config.threshold = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 3;
                        text: round(config.threshold);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.threshold = text.to-float().clamp(0, 255);
                            threshold-sl.value = config.threshold;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "threshold", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "threshold", VEFilter.make-float-value(config.threshold));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Strength");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;
                        strength-sl := Slider {
                            minimum: 0.0;
                            maximum: 2.0;
                            value: config.strength;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.strength = value;
                            }

                            released(value) => {
                                config.strength = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 3;
                        text: config.strength.to-fixed(1);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.strength = text.to-float().clamp(0, 2);
                            strength-sl.value = config.strength;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;
                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "strength", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "strength", VEFilter.make-float-value(config.strength));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Edge Color");
                enabled: selected-filter.enabled;
            }

            LineInput {
                read-only: true;
                is-show-icon: true;
                enabled: selected-filter.enabled;
                text: Util.color-picker-str(config.edge-color-r, config.edge-color-g, config.edge-color-b, config.edge-color-a);
                is-show-color-block: true;
                color-block-color: Util.color-picker-hex-color(self.text);
                icon: Icons.color-picker-light;
                border-color: Theme.is-dark ? Theme.base-border-color.brighter(20%) : Theme.base-border-color.darker(10%);

                changed has-focus => {
                    if (!self.has-focus) {
                        Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                    }
                }

                clicked => {
                    Store.video-editor-color-picker-id = Store.video-editor-color-picker-id + 1;
                    root.video-editor-color-picker-id-edge = Store.video-editor-color-picker-id;
                    Store.video-editor-color-picker-color = Util.color-picker-hex-color(self.text);
                    Store.video-editor-color-picker-toggle-flag = !Store.video-editor-color-picker-toggle-flag;
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Background");
                enabled: selected-filter.enabled;
            }

            LineInput {
                read-only: true;
                is-show-icon: true;
                enabled: selected-filter.enabled;
                text: Util.color-picker-str(config.background-color-r, config.background-color-g, config.background-color-b, config.background-color-a);
                is-show-color-block: true;
                color-block-color: Util.color-picker-hex-color(self.text);
                icon: Icons.color-picker-light;
                border-color: Theme.is-dark ? Theme.base-border-color.brighter(20%) : Theme.base-border-color.darker(10%);

                changed has-focus => {
                    if (!self.has-focus) {
                        Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                    }
                }

                clicked => {
                    Store.video-editor-color-picker-id = Store.video-editor-color-picker-id + 1;
                    root.video-editor-color-picker-id-bg = Store.video-editor-color-picker-id;
                    Store.video-editor-color-picker-color = Util.color-picker-hex-color(self.text);
                    Store.video-editor-color-picker-toggle-flag = !Store.video-editor-color-picker-toggle-flag;
                }
            }
        }

        SettingDetailSwitch {
            enabled: selected-filter.enabled;
            icon: Icons.invert-light;
            icon-size: Theme.icon-size * 0.7;
            text: Logic.tr("Invert");
            checked: config.invert;
            gain-focus-when-clicked: false;
            background: Theme.thirdly-background;

            toggled => {
                config.invert = !config.invert;
                apply(index, config);
            }
        }

        VerticalLayout { }
    }
}
