import {
    Theme,
    Logic,
    Store,
    Util,
    KeyframeValueType,
    KeyframeValue,
} from "../../../../../def.slint";
import {
    ClickAndEditLabel,
    Label,
    LineInput,
    Slider,
    SettingDetailInner,
    SettingDetailInnerVbox,
    SettingDetailLabel,
} from "../../../../../../base/widgets.slint";
import {
    VEFilter,
    SegmentFilter,
    LiquidGlassDetail,
} from "../../../filter.slint";
import { KeyframeButton } from "../keyframe-btn.slint";
import { Icons } from "../../../../../../base/icon.slint";

export component LiquidGlass inherits Rectangle {
    in-out property <int> index: -1;
    in-out property <SegmentFilter> selected-filter;
    in-out property <LiquidGlassDetail> config: VEFilter.from-liquid-glass-json(selected-filter.detail);
    in-out property <bool> color-picker-confirmed-flag: Store.video-editor-color-picker-confirmed-flag;
    in-out property toggle-keyframe-flag <=> VEFilter.toggle-keyframe-flag;
    private property <int> video-editor-color-picker-id;

    changed color-picker-confirmed-flag => {
        if (video-editor-color-picker-id != Store.video-editor-color-picker-id) {
            return;
        }
        let c = Store.video-editor-color-picker-color;
        config.tint-color-r = c.red;
        config.tint-color-g = c.green;
        config.tint-color-b = c.blue;
        apply(index, config);
    }

    callback apply(index: int, config: LiquidGlassDetail);

    changed selected-filter => {
        if (selected-filter.name == "liquid glass") {
            self.config = VEFilter.from-liquid-glass-json(selected-filter.detail);
            corner-radius-sl.value = self.config.corner-radius;
            refraction-height-sl.value = self.config.refraction-height;
            refraction-amount-sl.value = self.config.refraction-amount;
            blur-radius-sl.value = self.config.blur-radius;
            chromatic-aberration-sl.value = self.config.chromatic-aberration;
            depth-effect-sl.value = self.config.depth-effect;
            contrast-sl.value = self.config.contrast;
            white-point-sl.value = self.config.white-point;
            saturation-sl.value = self.config.chroma-multiplier;
            tint-alpha-sl.value = self.config.tint-alpha;
        }
    }

    SettingDetailInner {
        interactive: false;

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Position");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                LineInput {
                    enabled: selected-filter.enabled;
                    input-type: InputType.decimal;
                    text: config.x.to-fixed(2);
                    read-only: true;

                    changed has-focus => {
                        if (!self.has-focus) {
                            Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                        }
                    }
                }

                Label {
                    text: "X";
                    enabled: selected-filter.enabled;
                }

                LineInput {
                    enabled: selected-filter.enabled;
                    input-type: InputType.decimal;
                    text: config.y.to-fixed(2);
                    read-only: true;

                    changed has-focus => {
                        if (!self.has-focus) {
                            Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "position", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "position", VEFilter.make-float2-value(config.x, config.y));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Size");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                LineInput {
                    enabled: selected-filter.enabled;
                    input-type: InputType.decimal;
                    text: config.width.to-fixed(2);
                    read-only: true;

                    changed has-focus => {
                        if (!self.has-focus) {
                            Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                        }
                    }
                }

                Label {
                    enabled: selected-filter.enabled;
                    text: "X";
                }

                LineInput {
                    enabled: selected-filter.enabled;
                    input-type: InputType.decimal;
                    text: config.height.to-fixed(2);
                    read-only: true;

                    changed has-focus => {
                        if (!self.has-focus) {
                            Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "size", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "size", VEFilter.make-float2-value(config.width, config.height));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Corner Radius");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        corner-radius-sl := Slider {
                            minimum: 0.0;
                            maximum: 1080.0;
                            value: config.corner-radius;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.corner-radius = value;
                            }

                            released(value) => {
                                config.corner-radius = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 4;
                        text: round(config.corner-radius);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.corner-radius = text.to-float().clamp(0, 1080);
                            corner-radius-sl.value = config.corner-radius;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "corner_radius", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "corner_radius", VEFilter.make-float-value(config.corner-radius));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Refraction Height");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        refraction-height-sl := Slider {
                            minimum: 0.0;
                            maximum: 200.0;
                            value: config.refraction-height;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.refraction-height = value;
                            }

                            released(value) => {
                                config.refraction-height = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 4;
                        text: round(config.refraction-height);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.refraction-height = text.to-float().clamp(0, 200);
                            refraction-height-sl.value = config.refraction-height;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "refraction_height", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "refraction_height", VEFilter.make-float-value(config.refraction-height));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Refraction Amount");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        refraction-amount-sl := Slider {
                            minimum: 0.0;
                            maximum: 200.0;
                            value: config.refraction-amount;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.refraction-amount = value;
                            }

                            released(value) => {
                                config.refraction-amount = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 4;
                        text: round(config.refraction-amount);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.refraction-amount = text.to-float().clamp(0, 200);
                            refraction-amount-sl.value = config.refraction-amount;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "refraction_amount", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "refraction_amount", VEFilter.make-float-value(config.refraction-amount));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Blur Radius");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        blur-radius-sl := Slider {
                            minimum: 0.0;
                            maximum: 100.0;
                            value: config.blur-radius;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.blur-radius = value;
                            }

                            released(value) => {
                                config.blur-radius = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 4;
                        text: round(config.blur-radius);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.blur-radius = text.to-float().clamp(0, 100);
                            blur-radius-sl.value = config.blur-radius;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "blur_radius", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "blur_radius", VEFilter.make-float-value(config.blur-radius));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Chromatic Aberration");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        chromatic-aberration-sl := Slider {
                            minimum: 0.0;
                            maximum: 2.0;
                            value: config.chromatic-aberration;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.chromatic-aberration = value;
                            }

                            released(value) => {
                                config.chromatic-aberration = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 4;
                        text: config.chromatic-aberration.to-fixed(2);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.chromatic-aberration = text.to-float().clamp(0, 2);
                            chromatic-aberration-sl.value = config.chromatic-aberration;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "chromatic_aberration", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "chromatic_aberration", VEFilter.make-float-value(config.chromatic-aberration));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Depth Effect");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        depth-effect-sl := Slider {
                            minimum: -2.0;
                            maximum: 2.0;
                            value: config.depth-effect;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.depth-effect = value;
                            }

                            released(value) => {
                                config.depth-effect = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 4;
                        text: config.depth-effect.to-fixed(2);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.depth-effect = text.to-float().clamp(-2, 2);
                            depth-effect-sl.value = config.depth-effect;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "depth_effect", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "depth_effect", VEFilter.make-float-value(config.depth-effect));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Contrast");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        contrast-sl := Slider {
                            minimum: -1.0;
                            maximum: 1.0;
                            value: config.contrast;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.contrast = value;
                            }

                            released(value) => {
                                config.contrast = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 4;
                        text: config.contrast.to-fixed(2);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.contrast = text.to-float().clamp(-1, 1);
                            contrast-sl.value = config.contrast;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "contrast", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "contrast", VEFilter.make-float-value(config.contrast));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("White Point");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        white-point-sl := Slider {
                            minimum: -1.0;
                            maximum: 1.0;
                            value: config.white-point;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.white-point = value;
                            }

                            released(value) => {
                                config.white-point = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 4;
                        text: config.white-point.to-fixed(2);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.white-point = text.to-float().clamp(-1, 1);
                            white-point-sl.value = config.white-point;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "white_point", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "white_point", VEFilter.make-float-value(config.white-point));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Saturation");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        saturation-sl := Slider {
                            minimum: 0.0;
                            maximum: 2.0;
                            value: config.chroma-multiplier;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.chroma-multiplier = value;
                            }

                            released(value) => {
                                config.chroma-multiplier = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 4;
                        text: config.chroma-multiplier.to-fixed(2);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.chroma-multiplier = text.to-float().clamp(0, 2);
                            saturation-sl.value = config.chroma-multiplier;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "chroma_multiplier", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "chroma_multiplier", VEFilter.make-float-value(config.chroma-multiplier));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Tint Alpha");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        tint-alpha-sl := Slider {
                            minimum: 0.0;
                            maximum: 1.0;
                            value: config.tint-alpha;
                            indicator-size: Theme.default-font-size;
                            height: self.indicator-size * 0.3;
                            unfinished-progress-color: Theme.thirdly-background;
                            enabled: selected-filter.enabled;

                            changed(value) => {
                                config.tint-alpha = value;
                            }

                            released(value) => {
                                config.tint-alpha = value;
                                apply(index, config);
                            }
                        }
                    }

                    ClickAndEditLabel {
                        enabled: selected-filter.enabled;
                        use-fixed-width: true;
                        width: Theme.default-font-size * 4;
                        text: config.tint-alpha.to-fixed(2);
                        text-color: self.enabled ? Theme.primary-text-color : Theme.disabled-color;

                        accepted(text) => {
                            config.tint-alpha = text.to-float().clamp(0, 1);
                            tint-alpha-sl.value = config.tint-alpha;
                            apply(index, config);
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;

                    KeyframeButton {
                        enabled: selected-filter.enabled;
                        has-keyframe: VEFilter.property-has-keyframe-at-playhead(index, "tint_alpha", toggle-keyframe-flag);

                        clicked => {
                            VEFilter.toggle-keyframe-at-playhead(index, "tint_alpha", VEFilter.make-float-value(config.tint-alpha));
                            toggle-keyframe-flag = !toggle-keyframe-flag;
                        }
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Tint Color");
                enabled: selected-filter.enabled;
            }

            HorizontalLayout {
                spacing: Theme.spacing * 2;

                LineInput {
                    read-only: true;
                    is-show-icon: true;
                    enabled: selected-filter.enabled;
                    text: Util.color-picker-str(config.tint-color-r, config.tint-color-g, config.tint-color-b, 1.0);
                    is-show-color-block: true;
                    color-block-color: Util.color-picker-hex-color(self.text);
                    icon: Icons.color-picker-light;
                    border-color: Theme.is-dark ? Theme.base-border-color.brighter(20%) : Theme.base-border-color.darker(10%);
                    border-width: 1px;

                    changed has-focus => {
                        if (!self.has-focus) {
                            Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                        }
                    }

                    clicked => {
                        Store.video-editor-color-picker-id = Store.video-editor-color-picker-id + 1;
                        root.video-editor-color-picker-id = Store.video-editor-color-picker-id;
                        Store.video-editor-color-picker-color = Util.color-picker-hex-color(self.text);
                        Store.video-editor-color-picker-toggle-flag = !Store.video-editor-color-picker-toggle-flag;
                    }
                }
            }
        }

        VerticalLayout { }
    }
}
