import {
    Theme,
    Logic,
    Store,
} from "../../../../../def.slint";
import {
    IconBtn,
    CheckBtn,
    LineInput,
    SettingDetailInner,
    SettingDetailInnerVbox,
    SettingDetailLabel,
    SettingDetailSwitch,
    ConfirmDialogSetting,
} from "../../../../../../base/widgets.slint";
import {
    VEFilter,
    SegmentFilter,
    VideoFadeInDetail,
} from "../../../filter.slint";

export component VideoFadeIn inherits Rectangle {
    in-out property <int> index: -1;
    in-out property <SegmentFilter> selected-filter;
    in-out property <VideoFadeInDetail> config: VEFilter.from-video-fade-in-json(selected-filter.detail);

    callback apply(index: int, config: VideoFadeInDetail);

    SettingDetailInner {
        interactive: false;

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Duration (ms)");
                enabled: selected-filter.enabled;
            }

            LineInput {
                enabled: selected-filter.enabled;
                input-type: number;
                text: config.duration-ms;
                border-color: self.has-focus ? Theme.thirdly-brand-color : Theme.is-dark ? Theme.base-border-color.brighter(20%) : Theme.base-border-color.darker(10%);

                changed has-focus => {
                    if (!self.has-focus) {
                        Store.video-editor-focus-flag = !Store.video-editor-focus-flag;
                    }
                }

                accepted => {
                    config.duration-ms = round(self.text.to-float());
                    apply(index, config);
                }
            }
        }

        VerticalLayout { }
    }
}