import {
    Theme,
    Icons,
    Util,
    Logic,
    Store,
    SettingShareScreenClient,
    ConnectionStatus,
} from "../def.slint";
import {
    VideoPlayer,
    SwitchBtn,
    Label,
    LineInput,
    TextBtnWithoutIcon,
    GentleBackground,
} from "../../base/widgets.slint";

export component ShareScreenPanel inherits Rectangle {
    private property <int> play-time;
    private property <color> text-color: Theme.light-text-color.darker(30%);
    private property <color> disabled-text-color: Theme.light-text-color.darker(80%);
    private property <SettingShareScreenClient> cache-setting;
    private property <length> video-player-normal-width: Math.max(root.width * Theme.golden-ratio, Theme.default-width - Theme.padding * 8);
    private property <length> video-player-normal-height: Math.min(root.video-player-normal-width * 9 / 16, root.height * Theme.golden-ratio);

    init => {
        cache-setting = Logic.get-setting-share-screen-client();
    }

    Timer {
        interval: 1s;
        running: Store.share-screen-client-connection-status == ConnectionStatus.Connected;

        triggered() => {
            if (vp.is-playing) {
                play-time += 1;
            } else {
                play-time = 0;
            }
        }
    }

    GentleBackground { }

    VerticalLayout {
        alignment: center;
        spacing: Theme.spacing * 10;

        if !vp.is-full-screen: VerticalLayout {
            spacing: Theme.spacing * 8;

            HorizontalLayout {
                alignment: center;

                Label {
                    font-size: 36px;
                    font-weight: Theme.bold-font-weight;
                    text: Logic.tr("Wayshot Screen Sharing");
                    color: root.text-color;
                }
            }

            HorizontalLayout {
                alignment: center;
                spacing: Theme.spacing * 8;

                auth-inner-hbox := HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    VerticalLayout {
                        alignment: center;

                        SwitchBtn {
                            checked: cache-setting.enable-auth;

                            toggled => {
                                cache-setting.enable-auth = !cache-setting.enable-auth;
                            }
                        }
                    }

                    Label {
                        vertical-alignment: center;
                        text: Logic.tr("Auth");
                        color: cache-setting.enable-auth ? root.text-color : root.disabled-text-color;
                    }
                }

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    Label {
                        text: Logic.tr("Token") + ":";
                        color: cache-setting.enable-auth ? root.text-color : root.disabled-text-color;
                    }

                    token-li := LineInput {
                        private property <bool> show-password;

                        is-show-icon: true;
                        width: min(vp.width * 0.2, 150px);
                        read-only: !cache-setting.enable-auth;
                        text: cache-setting.auth-token;
                        placeholder-text: "eg: 123";
                        icon-colorize: self.text-color;
                        icon: show-password ? Icons.eye-light : Icons.close-eye-light;
                        input-type: show-password ? InputType.text : InputType.password;
                        text-color: cache-setting.enable-auth ? root.text-color : root.disabled-text-color;
                        border-color: self.has-focus ? Theme.thirdly-brand-color : root.disabled-text-color.darker(30%);
                        placeholder-text-color: root.disabled-text-color.darker(50%);

                        clicked => {
                            show-password = !show-password;
                        }
                    }
                }

                HorizontalLayout {
                    spacing: Theme.spacing * 4;

                    Label {
                        text: Logic.tr("Server") + ":";
                        color: root.text-color;
                    }

                    addr-li := LineInput {
                        width: min(vp.width * 0.2, 200px);
                        text: cache-setting.server-addr;
                        placeholder-text: "http://192.168.0.10:9090";
                        text-color: root.text-color;
                        border-color: self.has-focus ? Theme.thirdly-brand-color : root.disabled-text-color.darker(30%);
                        placeholder-text-color: root.disabled-text-color.darker(50%);
                    }
                }

                VerticalLayout {
                    alignment: center;

                    TextBtnWithoutIcon {
                        vpadding: Theme.padding * 2;
                        hpadding: Theme.padding * 4;
                        text-color: Theme.light-text-color;
                        font-weight: Theme.bold-font-weight;
                        text: Store.share-screen-client-connection-status == ConnectionStatus.Disconnected ? Logic.tr("Connect") : (Store.share-screen-client-connection-status == ConnectionStatus.Connected ? Logic.tr("Disconnect") : Logic.tr("Connecting"));
                        background: Store.share-screen-client-connection-status == ConnectionStatus.Disconnected ? Theme.thirdly-brand-color : (Store.share-screen-client-connection-status == ConnectionStatus.Connected ? Theme.danger-color : Theme.warning-color);

                        clicked => {
                            if (Store.share-screen-client-connection-status == ConnectionStatus.Disconnected) {
                                cache-setting.auth-token = token-li.text;
                                cache-setting.server-addr = addr-li.text;
                                Logic.set-setting-share-screen-client(cache-setting);
                                Logic.share-screen-client-connect(cache-setting);
                            } else {
                                Logic.share-screen-client-disconnect();
                            }
                        }
                    }
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            height: vp.height;

            vp := VideoPlayer {
                width: self.is-full-screen ? root.width : root.video-player-normal-width;
                height: self.is-full-screen ? root.height : root.video-player-normal-height;
                border-radius: Theme.border-radius;
                show-speed-btn: false;
                show-progress-bar: false;
                show-subtitle-btn: false;
                current-sound: 50;
                player-image: Store.share-screen-player-image;
                time-label: Logic.convert-to-meida-time(root.play-time);
                is-real-time-player-mode: true;
                is-loading: ConnectionStatus.Connecting == Store.share-screen-client-connection-status;

                private property <ConnectionStatus> connection-status: Store.share-screen-client-connection-status;

                changed connection-status => {
                    self.is-playing = self.connection-status == ConnectionStatus.Connected;
                    play-time = 0;
                }

                play() => {
                    if (Store.share-screen-client-connection-status == ConnectionStatus.Connected) {
                        vp.is-playing = true;
                        Logic.share-screen-player-play();
                    } else {
                        vp.is-playing = false;
                    }
                }

                stop() => {
                    if (Store.share-screen-client-connection-status == ConnectionStatus.Connected) {
                        vp.is-playing = false;
                        Logic.share-screen-player-stop();
                    } else {
                        vp.is-playing = false;
                    }
                }

                sound-changed(sound) => {
                    Logic.share-screen-player-sound-changed(sound);
                }
            }
        }
    }
}
