import {
    Store,
    Logic,
    Theme,
    DeviceType,
    Icons,
    SettingRecorder,
    SettingCursorTracker,
} from "../../def.slint";
import {
    SettingDetail,
    SettingDetailInner,
    RadioBtn,
    SettingDetailInnerVbox,
    SettingDetailLabel,
    LineInput,
    ConfirmBtn,
    Label,
    SettingDetailSwitch,
    Select,
} from "../../../base/widgets.slint";

export component CursorTracker inherits SettingDetail {
    callback confirmed();

    private property <SettingCursorTracker> setting;

    init => {
        root.set(Logic.get-setting-cursor-tracker());
    }

    public function get() -> SettingCursorTracker {
        root.setting.stable-radius = stable-radius-li.text.to-float();
        root.setting.fast-moving-duration = fast-moving-duration-li.text.to-float();
        root.setting.linear-transition-duration = linear-transition-duration-li.text.to-float();
        root.setting.max-stable-region-duration = max-stable-region-duration-li.text.to-float();
        return root.setting;
    }

    public function set(setting: SettingCursorTracker) {
        root.setting = setting;
    }

    SettingDetailInner {
        SettingDetailInnerVbox {
            SettingDetailSwitch {
                icon: Icons.tracker-light;
                text: self.checked ? Logic.tr("Enabled cursor tracking") : Logic.tr("Disabled cursor tracking");
                checked: root.setting.enable-tracking;

                toggled => {
                    root.setting.enable-tracking = self.checked;
                }
            }
        }

        VerticalLayout {
            visible: root.setting.enable-tracking;
            spacing: Theme.spacing * 4;

            SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("Region size(width x height)");
                }

                HorizontalLayout {
                    spacing: Theme.spacing * 2;

                    region-width-li := LineInput {
                        horizontal-stretch: 1;
                        input-type: number;
                        placeholder-text: "1280px";
                        text: root.setting.region-width;
                    }

                    Label {
                        text: "X";
                    }

                    region-height-li := LineInput {
                        horizontal-stretch: 1;
                        input-type: number;
                        placeholder-text: "720px";
                        text: root.setting.region-height;
                    }
                }
            }

            SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("Stable radius(pixel)");
                }

                stable-radius-li := LineInput {
                    input-type: InputType.number;
                    placeholder-text: "15px";
                    icon: Icons.file-open-light;
                    text: root.setting.stable-radius;
                }
            }

            SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("Fast moving interval(milliseconds)");
                }

                fast-moving-duration-li := LineInput {
                    input-type: InputType.number;
                    placeholder-text: "100ms";
                    text: root.setting.fast-moving-duration;
                }
            }

            SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("Linear transition duration(milliseconds)");
                }

                linear-transition-duration-li := LineInput {
                    input-type: InputType.number;
                    placeholder-text: "1000ms";
                    text: root.setting.linear-transition-duration;
                }
            }

            SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("Maximum duration of stay in the stable region(seconds)");
                }

                max-stable-region-duration-li := LineInput {
                    input-type: InputType.number;
                    placeholder-text: "5s";
                    text: root.setting.max-stable-region-duration;
                }
            }
        }
    }
}
