import {
    Store,
    Logic,
    Theme,
    DeviceType,
    Icons,
    SettingShareScreen,
} from "../../def.slint";
import { Fps, Resolution } from "../../../store.slint";
import {
    SettingDetail,
    SettingDetailInner,
    RadioBtn,
    SettingDetailInnerVbox,
    SettingDetailLabel,
    LineInput,
    ConfirmBtn,
    Label,
    SettingDetailSwitch,
} from "../../../base/widgets.slint";
import { Tag } from "../../../base/tag.slint";

export component ShareScreen inherits SettingDetail {
    callback confirmed();

    private property <SettingShareScreen> cache-setting;

    init => {
        root.set(Logic.get-setting-share-screen());
    }

    public function get() -> SettingShareScreen {
        return root.cache-setting;
    }

    public function set(setting: SettingShareScreen) {
        cache-setting = setting;
        Store.setting-share-screen-cert-file = cache-setting.cert-file;
        Store.setting-share-screen-key-file = cache-setting.key-file;
    }

    SettingDetailInner {
        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Listen address");
                tip: Logic.tr("HTTP server listen address");
            }

            LineInput {
                text: cache-setting.listen-addr;
                placeholder-text: "0.0.0.0:9090";
                border-color: self.text != cache-setting.listen-addr ? Theme.danger-color : self.default-border-color;

                accepted => {
                    if (!self.text.is-empty) {
                        cache-setting.listen-addr = self.text;
                    }
                }
            }
        }

        VerticalLayout {
            spacing: Theme.spacing * 2;

            SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("Host ips (optional)");
                    tip: Logic.tr("NAT 1to1 ips");
                }

                LineInput {
                    is-show-icon: true;
                    icon: Icons.add-with-rect-light;
                    placeholder-text: "192.168.0.1";

                    accepted => {
                        self.clicked();
                    }

                    clicked => {
                        if (!self.text.is-empty) {
                            Logic.share-screen-add-host-ip(cache-setting.host-ips, self.text);
                            self.text = "";
                        }
                        self.focus();
                    }
                }
            }

            if cache-setting.host-ips.length > 0: HorizontalLayout {
                alignment: start;
                spacing: Theme.spacing * 2;
                for ip[index] in cache-setting.host-ips: Tag {
                    text: ip;
                    is-show-close-btn: true;
                    background: Theme.tag-colors[Math.mod(index, Theme.tag-colors.length)];

                    close => {
                        Logic.share-screen-remove-host-ip(cache-setting.host-ips, index);
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            SettingDetailLabel {
                text: Logic.tr("Auth token (optional)");
                tip: Logic.tr("HTTP server auth token");
            }

            LineInput {
                text: cache-setting.auth_token;
                placeholder-text: "123456";
                border-color: self.text != cache-setting.auth-token ? Theme.danger-color : self.default-border-color;

                accepted => {
                    if (!self.text.is-empty) {
                        cache-setting.auth_token = self.text;
                    }
                }
            }
        }

        VerticalLayout {
            spacing: Theme.spacing;

            SettingDetailInnerVbox {
                SettingDetailSwitch {
                    icon: Icons.stun-light;
                    text: Logic.tr("STUN server");
                    checked: cache-setting.enable-stun-server;

                    toggled => {
                        cache-setting.enable-stun-server = self.checked;
                    }
                }
            }

            if cache-setting.enable-stun-server: SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("URL");
                }

                LineInput {
                    text: cache-setting.stun_server.url;
                    placeholder-text: "stun:192.168.0.1:3478";
                    border-color: self.text != cache-setting.stun-server.url ? Theme.danger-color : self.default-border-color;

                    accepted => {
                        if (!self.text.is-empty) {
                            cache-setting.stun-server.url = self.text;
                        }
                    }
                }
            }

            if cache-setting.enable-stun-server: SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("User name (optional)");
                }

                LineInput {
                    text: cache-setting.stun-server.username;
                    placeholder-text: "username";
                    border-color: self.text != cache-setting.stun-server.username ? Theme.danger-color : self.default-border-color;

                    accepted => {
                        if (!self.text.is-empty) {
                            cache-setting.stun-server.username = self.text;
                        }
                    }
                }
            }

            if cache-setting.enable-stun-server: SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("Password (optional)");
                }

                LineInput {
                    private property <bool> show-password;

                    is-show-icon: true;
                    placeholder-text: "password";
                    icon: show-password ? Icons.eye-light : Icons.close-eye-light;
                    text: cache-setting.stun-server.credential;
                    input-type: show-password ? InputType.text : InputType.password;
                    border-color: self.text != cache-setting.stun-server.credential ? Theme.danger-color : self.default-border-color;

                    clicked => {
                        show-password = !show-password;
                    }

                    accepted => {
                        if (!self.text.is-empty) {
                            cache-setting.stun-server.credential = self.text;
                        }
                    }
                }

                Label {
                    wrap: word-wrap;
                    color: Theme.danger-color;
                    text: Logic.tr("The password will be sent to the client. Please enable authentication and TLS, and ensure the client is trusted.");
                }
            }
        }

        VerticalLayout {
            spacing: Theme.spacing;

            SettingDetailInnerVbox {
                SettingDetailSwitch {
                    icon: Icons.cloud-server-light;
                    text: Logic.tr("TURN server");
                    checked: cache-setting.enable-turn-server;

                    toggled => {
                        cache-setting.enable-turn-server = self.checked;
                    }
                }
            }

            if cache-setting.enable-turn-server: SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("URL");
                }

                LineInput {
                    text: cache-setting.turn_server.url;
                    placeholder-text: "turn:192.168.0.1:3478";
                    border-color: self.text != cache-setting.turn-server.url ? Theme.danger-color : self.default-border-color;

                    accepted => {
                        if (!self.text.is-empty) {
                            cache-setting.turn-server.url = self.text;
                        }
                    }
                }
            }

            if cache-setting.enable-turn-server: SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("User name (optional)");
                }

                LineInput {
                    text: cache-setting.turn_server.username;
                    placeholder-text: "username";
                    border-color: self.text != cache-setting.turn-server.username ? Theme.danger-color : self.default-border-color;

                    accepted => {
                        if (!self.text.is-empty) {
                            cache-setting.turn-server.username = self.text;
                        }
                    }
                }
            }

            if cache-setting.enable-turn-server: SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("Password (optional)");
                }

                LineInput {
                    private property <bool> show-password;

                    is-show-icon: true;
                    placeholder-text: "password";
                    text: cache-setting.turn_server.credential;
                    icon: show-password ? Icons.eye-light : Icons.close-eye-light;
                    input-type: show-password ? InputType.text : InputType.password;
                    border-color: self.text != cache-setting.turn-server.credential ? Theme.danger-color : self.default-border-color;

                    clicked => {
                        show-password = !show-password;
                    }

                    accepted => {
                        if (!self.text.is-empty) {
                            cache-setting.turn-server.credential = self.text;
                        }
                    }
                }

                Label {
                    wrap: word-wrap;
                    color: Theme.danger-color;
                    text: Logic.tr("The password will be sent to the client. Please enable authentication and TLS, and ensure the client is trusted.");
                }
            }
        }

        VerticalLayout {
            spacing: Theme.spacing;

            SettingDetailInnerVbox {
                SettingDetailSwitch {
                    icon: Icons.https-light;
                    text: self.checked ? Logic.tr("Enabled TLS") : Logic.tr("Disabled TLS");
                    checked: cache-setting.enable-https;

                    toggled => {
                        cache-setting.enable-https = self.checked;
                    }
                }
            }

            if cache-setting.enable-https: SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("Certification");
                }

                LineInput {
                    read-only: true;
                    is-show-icon: true;
                    icon: Icons.file-open-light;
                    text: Store.setting-share-screen-cert-file;
                    placeholder-text: "*.crt or *.pem";

                    changed text => {
                        cache-setting.cert-file = self.text;
                    }

                    clicked => {
                        Logic.share-screen-load-cert-file();
                    }
                }
            }

            if cache-setting.enable-https: SettingDetailInnerVbox {
                SettingDetailLabel {
                    text: Logic.tr("Private key");
                }

                LineInput {
                    read-only: true;
                    is-show-icon: true;
                    icon: Icons.file-open-light;
                    text: Store.setting-share-screen-key-file;
                    placeholder-text: "*.key or *.pem";

                    changed text => {
                        cache-setting.key-file = self.text;
                    }

                    clicked => {
                        Logic.share-screen-load-key-file();
                    }
                }
            }
        }

        SettingDetailInnerVbox {
            spacing: Theme.spacing * 2;

            SettingDetailSwitch {
                icon: Icons.ipv6-light;
                text: self.checked ? Logic.tr("Enabled IPV6") : Logic.tr("Disabled IPV6");
                checked: !cache-setting.disable-host-ipv6;

                toggled => {
                    cache-setting.disable-host-ipv6 = !self.checked;
                }
            }
        }

        SettingDetailInnerVbox {
            save-mp4-swicth := SettingDetailSwitch {
                icon: Icons.save-archive-light;
                text: self.checked ? Logic.tr("Save mp4") : Logic.tr("Don't save mp4");
                checked: cache-setting.save-mp4;

                toggled => {
                    cache-setting.save-mp4 = self.checked;
                }
            }
        }
    }
}
