import "fonts/NotoSansMonoCJKsc-Regular.otf";
import "fonts/SourceHanSerifCN.ttf";
import "fonts/SourceHanSansCN.otf";

import {
    Util,
    Logic,
    Theme,
    Icons,
    Store,
    DeviceType,
    VEFilter,
    TerminalState,
    TermSpan,
    TermTabModel,
    TabIndex,
} from "panel/def.slint";
import {
    Toast,
    IconsDialogSetting,
    IconsDialog,
    ConfirmDialog,
    ConfirmDialogSetting,
    MessageDialog,
    MessageDialogSetting,
    Blanket,
    LandingPage,
    AboutSetting,
    ToastSetting,
    PopupActionSetting,
    UpdateDialog,
} from "base/widgets.slint";
import { DesktopPanel } from "panel/desktop/desktop.slint";

export component AppWindow inherits Window {
    // width: Theme.default-width;
    // height: Theme.default-height;
    preferred-width: Theme.default-width;
    preferred-height: Theme.default-height;
    default-font-size: Theme.default-font-size;
    default-font-weight: Theme.normal-font-weight;
    default-font-family: Theme.default-font-family;
    background: Theme.base-background;
    icon: Icons.brand;
    title: AboutSetting.app-name + video-editor-project-name;
    no-frame: Store.setting-preference.no-frame;
    always-on-top: Store.setting-preference.always-on-top;

    private property <string> video-editor-project-name: Store.current-tab-index != TabIndex.VideoEditor ? "" : " (" + (Store.video-editor-new-project-config.name.is-empty ? Logic.tr("Untitled") : Store.video-editor-new-project-config.name) + (Store.video-editor-is-unsaved ? "*" : "") + ")";

    DesktopPanel {
        title: root.title;
    }

    if IconsDialogSetting.show || ConfirmDialogSetting.show || MessageDialogSetting.show || Store.is-show-update-dialog:  Blanket {
        clicked => {
            IconsDialogSetting.show = false;
            ConfirmDialogSetting.show = false;
            MessageDialogSetting.show = false;
            Store.is-show-update-dialog = false;
        }
    }

    if IconsDialogSetting.show: IconsDialog {
        is-prevent-event-forward: true;
        column-count: Store.device-type == DeviceType.Desktop ? 6 : 5;
        icon-size: Store.device-type == DeviceType.Desktop ? Theme.icon-size * 3 : Theme.icon-size;
        select-index(handle-type, index, user-data) => {
        }
    }

    if ConfirmDialogSetting.show: ConfirmDialog {
        is-prevent-event-forward: true;
        gain-focus-when-clicked: false;
        width: Math.min(root.width * 0.9, self.vbox-preferred-width * 2);
    }

    if MessageDialogSetting.show: MessageDialog {
        is-prevent-event-forward: true;
        width: Math.min(root.width * 0.9, self.vbox-preferred-width * 2);
    }

    if Store.is-show-update-dialog: UpdateDialog {
        app-name: AboutSetting.app-name;
        current-version: AboutSetting.version;
        latest-version: Store.latest-version;
        update-content: Store.update-content;
        confirm-icon: Icons.download-light;
        confirm-text: Logic.tr("Download");

        escape => {
            Store.is-show-update-dialog = false;
        }

        canceled => {
            Store.is-show-update-dialog = false;
            if self.dont-ask-again {
                Logic.update-dialog-dont-ask-again(Store.latest-version);
            }
        }

        confirmed => {
            Store.is-show-update-dialog = false;
            if self.dont-ask-again {
                Logic.update-dialog-dont-ask-again(Store.latest-version);
            }
            Util.open-url("Default", "https://github.com/heng30/wayshot/releases");
        }
    }

    if !ToastSetting.is-timeout || ToastSetting.is-hover: Toast {
        x: root.width / 2 - self.width / 2;
        y: 50px;
        width: Math.min(root.width * 80%, self.preferred-width);
        clicked => {
            Logic.copy-to-clipboard(ToastSetting.text);
        }
    }

    if Store.is-show-landing-page: LandingPage {
        details: [
            {
                picture: Icons.landing-account,
                description: Store.is-cn ? "这是一个视频创作工具：视频编辑、录屏、直播和屏幕共享" : "Video creation tool: Video editing, screen recording, streaming, and screen sharing",
            },
            {
                picture: Icons.landing-send,
                description: Store.is-cn ? "多轨时间线编辑，46 种视频滤镜，12 种音频滤镜，关键帧动画" : "Multi-track timeline, 46 video filters, 12 audio filters, keyframe animation",
            },
            {
                picture: Icons.landing-welcome,
                description: Store.is-cn ? "内置丰富 AI 功能，欢迎使用" : "Built-in rich AI features, welcome to use",
            }
        ];
        skipped => {
            Store.is-show-landing-page = false;
        }
    }
}

export {
    Util,
    Logic,
    Store,
    Theme,
    Icons,
    AboutSetting,
    PopupActionSetting,
    ToastSetting,
    ConfirmDialogSetting,
    VEFilter,
    TerminalState,
    TermSpan,
    TermTabModel,
}
