import {
    Store,
    SettingPreference,
    TabIndex,
    SettingDetailIndex,
    MobileSettingDetailIndex,
    PopupIndex,
    MobileTabIndex,
    SettingBackup,
    SettingRecorder,
    SettingControl,
    SettingPlayer,
    SettingCursorTracker,
    SettingShareScreen,
    Fps,
    Resolution,
    HistoryEntry,
    ProcessMode,
    SettingShareScreenClient,
    SettingPushStream,
    SettingCamera,
    RealtimeImageEffect,
    BackgroundRemoverModel,
    DownloaderState,
    TranscribeProgressType,
    Subtitle,
    SettingTranscribe,
} from "store.slint";

import { Theme } from "base/theme.slint";

export global Logic {
    callback caches-size() -> string;
    callback remove-caches();

    callback copy-to-clipboard(text: string);
    callback paste-from-clipboard() -> string;

    callback get-setting-preference() -> SettingPreference;
    callback set-setting-preference(setting: SettingPreference);

    callback increase-font-size();
    callback decrease-font-size();

    callback backup(setting: SettingBackup);
    callback recover();
    callback uninstall();

    pure callback inner-tr(text: string, lang: string) -> string;
    inner-tr(text, lang) => {
        return text;
    }

    pure public function tr(text: string) -> string {
        return inner-tr(text, Store.setting-preference.language);
    }

    // desktop
    public function switch-tab(index: TabIndex) {
        if (Store.current-tab-index == TabIndex.Player) {
            Logic.player-stop();
        }
        if (Store.current-tab-index != index) {
            Store.previous-tab-index = Store.current-tab-index;
            Store.current-tab-index = index;
        }
    }

    //desktop
    public function switch-popup(index: PopupIndex) {
        if (Store.current-popup-index != index) {
            Store.current-popup-index = index;
        }
    }

    // desktop
    public function switch-setting-detail(index: SettingDetailIndex) {
        if (Store.current-setting-detail-index == index) {
            return;
        }
        Store.current-setting-detail-index = index;
    }

    public function switch-process-mode(mode: ProcessMode) {
        if (Store.process-mode == mode) {
            return;
        }
        Store.process-mode = mode;
    }

    // android
    public function switch-mobile-tab(index: MobileTabIndex) {
        if (Store.current-mobile-tab-index != index) {
            Store.previous-mobile-tab-index = Store.current-mobile-tab-index;
            Store.current-mobile-tab-index = index;
        }
    }

    // android
    public function switch-mobile-setting-detail(index: MobileSettingDetailIndex) {
        if (Store.current-mobile-setting-detail-index == index) {
            return;
        }
        Store.current-mobile-setting-detail-index = index;
    }

    //////////////////////////////// Logic Start  ////////////////////////////////
    callback get-setting-recorder() -> SettingRecorder;
    callback set-setting-recorder(setting: SettingRecorder);

    callback get-setting-control() -> SettingControl;
    callback set-setting-control(setting: SettingControl);
    callback toggle-control-enable-stats();
    callback toggle-control-enable-preview();

    callback get-setting-cursor-tracker() -> SettingCursorTracker;
    callback set-setting-cursor-tracker(setting: SettingCursorTracker);

    callback get-setting-share-screen() -> SettingShareScreen;
    callback set-setting-share-screen(setting: SettingShareScreen);

    callback get-setting-share-screen-client() -> SettingShareScreenClient;
    callback set-setting-share-screen-client(setting: SettingShareScreenClient);

    callback get-setting-push-stream() -> SettingPushStream;
    callback set-setting-push-stream(setting: SettingPushStream);

    callback get-setting-camera() -> SettingCamera;
    callback set-setting-camera(setting: SettingCamera);

    callback get-setting-transcribe() -> SettingTranscribe;
    callback set-setting-transcribe(setting: SettingTranscribe);

    callback init-sources-dialog();
    callback choose-save-dir();
    callback update-sources(setting: SettingControl);

    callback audio-changed(name: string, show-toast: bool);
    callback audio-gain-changed(value: float);

    callback refresh-speaker(show-toast: bool);
    callback speaker-gain-changed(value: float);

    callback start-recording();
    callback stop-recording();

    callback open-file(file: string);
    pure callback file-exist(file: string) -> bool;

    callback cal-region-width(height: float) -> int;
    callback cal-region-height(width: float) -> int;

    pure callback history-statistics(etries: [HistoryEntry], _flag: int) -> [int];
    callback toggle-sort-history();
    callback refresh-histories();
    callback add-history(file-path: string);
    callback remove-history(index: int);
    callback remove-no-found-histories();
    callback remove-all-histories();

    callback init-playlist();
    callback player-play-prev(index: int);
    callback player-play-next(index: int);
    callback player-play(index: int);
    callback player-stop();
    callback player-forward(index: int);
    callback player-backward(index: int);
    callback player-sound-changed(sound: int);
    callback player-progress-changed(index: int, progress: float);

    pure callback get-current-playlist-index() -> int;
    get-current-playlist-index => {
        return -1;
    }

    // share screen server
    callback share-screen-add-host-ip(host-ips: [string], ip: string);
    callback share-screen-remove-host-ip(host-ips: [string], index: int);
    callback share-screen-load-cert-file();
    callback share-screen-load-key-file();
    callback share-screen-verify-setting(setting: SettingShareScreen) -> string;

    // share screen client
    callback share-screen-player-play();
    callback share-screen-player-stop();
    callback share-screen-player-sound-changed(progress: float);
    callback share-screen-client-disconnect();
    callback share-screen-client-connect(setting: SettingShareScreenClient);

    callback push-stream-verify-setting(setting: SettingPushStream) -> string;

    callback camera-setting-dialog-start-playing(camera: string);
    callback camera-setting-dialog-stop-playing();
    callback choose-camera-backround-remover-model-path(model: BackgroundRemoverModel);
    callback camera-backround-remover-model-filename(model: BackgroundRemoverModel) -> string;
    callback camera-backround-remover-model-start-download(url: string, model: BackgroundRemoverModel);
    callback camera-backround-remover-model-cancel-download(url: string, model: BackgroundRemoverModel);

    callback show-realtime-image-effect-dialog(flag: bool);
    callback init-realtime-image-effect-dialog() -> RealtimeImageEffect;
    callback realtime-image-effect-changed(effect: RealtimeImageEffect);

    pure callback is-valid-subtitle-timestamp(timestamp: string) -> bool;
    pure callback ms-to-srt-timestamp-ui(ms: float) -> string;

    callback transcribe-init();
    callback transcribe-new();
    callback transcribe-start();
    callback transcribe-import-file();
    callback transcribe-export-video();
    callback transcribe-export-subtitles();
    callback transcribe-refresh-subtitles();
    callback transcribe-cancel-progress(ty: TranscribeProgressType);

    callback transcribe-subtitles-recovery();
    callback transcribe-subtitles-remove-all();
    callback transcribe-subtitles-correction();
    callback transcribe-subtitles-remove-correction();
    callback transcribe-subtitles-adjust-overlap-timestamp();
    callback transcribe-subtitles-to-lowercase();
    callback transcribe-subtitles-to-simple-chinese();
    callback transcribe-subtitles-to-primitive-numbers();
    callback transcribe-subtitles-remove-separator();
    callback transcribe-subtitles-replace-text(old-text: string, new-text: string);
    callback transcribe-subtitles-update-playng-index(progress: float);

    callback transcribe-subtitle-update(index: int, item: Subtitle);
    callback transcribe-subtitle-accept-correction(index: int);
    callback transcribe-subtitle-split(index: int);
    callback transcribe-subtitle-merge-above(index: int);
    callback transcribe-subtitle-insert-above(index: int);
    callback transcribe-subtitle-insert-below(index: int);
    callback transcribe-subtitle-remove(index: int);

    callback transcribe-choose-model-path(index: int);
    callback transcribe-model-cancel-download(index: int, url: string);
    callback transcribe-model-start-download(index: int, url: string);

    callback transcribe-audio-player-init();
    callback transcribe-audio-player-sound-changed(sound: float);
    callback transcribe-audio-player-sound-released(sound: float);
    callback transcribe-audio-player-progress-changed(value: float);
    callback transcribe-audio-player-progress-released(value: float);
    callback transcribe-audio-player-progress-pressed(value: float);

    callback transcribe-play-audio(start-timestamp: string, end-timestamp: string);
    callback transcribe-stop-audio();

    callback transcribe-sound-wave-update(index: int, max-samples: int);
    callback transcribe-sound-wave-zoom-changed(index: int, level: float);
    callback transcribe-sound-wave-moved(index: int, percent: float);
    callback transcribe-sound-wave-start-position-changed(index: int, pos: float);
    callback transcribe-sound-wave-end-position-changed(index: int, pos: float);

    pure public function fps-to-int(fps: Fps) -> int {
        if (fps == Fps.Fps24) {
            return 24;
        } else if (fps == Fps.Fps25) {
            return 25;
        } else if (fps == Fps.Fps30) {
            return 30;
        } else if (fps == Fps.Fps60) {
            return 60;
        } else {
            return 25;
        }
    }

    pure public function fps-from-int(fps: int) -> Fps {
        if (fps == 24) {
            return Fps.Fps24;
        } else if (fps == 25) {
            return Fps.Fps25;
        } else if (fps == 30) {
            return Fps.Fps30;
        } else if (fps == 60) {
            return Fps.Fps60;
        } else {
            return Fps.Fps25;
        }
    }

    pure public function resolution-to-string(res: Resolution) -> string {
        if (res == Resolution.Original) {
            return "Original";
        } else if (res == Resolution.P480) {
            return "480P";
        } else if (res == Resolution.P720) {
            return "720P";
        } else if (res == Resolution.P1080) {
            return "1080P";
        } else if (res == Resolution.P2K) {
            return "2K";
        } else if (res == Resolution.P4K) {
            return "4K";
        } else {
            return "Original";
        }
    }

    pure public function resolution-from-string(res: string) -> Resolution {
        if (res == "Original") {
            return Resolution.Original;
        } else if (res == "480P") {
            return Resolution.P480;
        } else if (res == "720P") {
            return Resolution.P720;
        } else if (res == "1080P") {
            return Resolution.P1080;
        } else if (res == "2K") {
            return Resolution.P2K;
        } else if (res == "4K") {
            return Resolution.P4K;
        } else {
            return Resolution.Original;
        }
    }

    pure public function image-effect-to-string(effect: RealtimeImageEffect) -> string {
        if (effect == RealtimeImageEffect.Grayscale) {
            return Logic.tr("Grayscale");
        } else if (effect == RealtimeImageEffect.Invert) {
            return Logic.tr("Invert");
        } else if (effect == RealtimeImageEffect.SnowNoise) {
            return Logic.tr("SnowNoise");
        } else if (effect == RealtimeImageEffect.SnowNoiseTV) {
            return Logic.tr("SnowNoiseTV");
        } else if (effect == RealtimeImageEffect.Rosetint) {
            return Logic.tr("Rosetint");
        } else if (effect == RealtimeImageEffect.Twenties) {
            return Logic.tr("Twenties");
        } else if (effect == RealtimeImageEffect.Mauve) {
            return Logic.tr("Mauve");
        } else if (effect == RealtimeImageEffect.Radio) {
            return Logic.tr("Radio");
        } else if (effect == RealtimeImageEffect.Bluechrome) {
            return Logic.tr("Bluechrome");
        } else if (effect == RealtimeImageEffect.Dramatic) {
            return Logic.tr("Dramatic");
        } else if (effect == RealtimeImageEffect.PastelPink) {
            return Logic.tr("Pastel Pink");
        } else if (effect == RealtimeImageEffect.Obsidian) {
            return Logic.tr("Obsidian");
        } else if (effect == RealtimeImageEffect.Pixelate) {
            return Logic.tr("Pixelate");
        } else if (effect == RealtimeImageEffect.Posterize) {
            return Logic.tr("Posterize");
        } else if (effect == RealtimeImageEffect.Sepia) {
            return Logic.tr("Sepia");
        } else if (effect == RealtimeImageEffect.Vignette) {
            return Logic.tr("Vignette");
        } else if (effect == RealtimeImageEffect.Temperature) {
            return Logic.tr("Temperature");
        } else {
            return Logic.tr("None");
        }
    }

    pure public function downloader-progress-color(state: DownloaderState) -> color {
        if (state == DownloaderState.Cancelled) {
            return Theme.warning-color;
        } else if (state == DownloaderState.Failed) {
            return Theme.danger-color;
        } else {
            return Theme.thirdly-brand-color;
        }
    }
    //////////////////////////////// Logic End  ////////////////////////////////
}
