export enum DeviceType {
    Desktop,
    Mobile,
    Web,
}

export enum FeatureType {
    Other,
    WaylandWlr,
    WaylandPortal,
    Windows,
}

export enum TabIndex {
    Home,
    History,
    Player,
    ShareScreen,
}

export enum PopupIndex {
    None,
    Help,
    About,
    Donate,
    Backup,
    Recover,
    Setting,

    Source,
}

export enum SettingDetailIndex {
    Preference,
    Recorder,
    CursorTracking,
    ShareScreen,
    PushStream,
}

export enum MobileTabIndex {
    Home,
    Setting,
}

export enum MobileSettingDetailIndex {
    Home,
    Preference,
    Proxy,
    Donate,
    About,
    Help,
}

export struct SettingPreference {
    win-width: string,
    win-height: string,
    font-size: string,
    font-family: string,
    language: string,
    always-on-top: bool,
    no-frame: bool,
    is-dark: bool,
}

export struct SettingBackup {
   configuration: bool,
   data: bool,
   cache: bool,
}

//////////////////////////////// Logic Struct Start ////////////////////////////////

export enum Fps {
    Fps24,
    Fps25,
    Fps30,
    Fps60,
}

export enum Resolution {
    Original,
    P480,
    P720,
    P1080,
    P2K,
    P4K,
}

export enum TransitionType {
    Linear,
    EaseIn,
    EaseOut,
}

export enum ProcessMode {
    RecordScreen,
    ShareScreen,
    PushStream,
}

export enum RealtimeImageEffect {
    None,
    Grayscale,
    Invert,
    SnowNoise,
    SnowNoiseTV,
    Rosetint,
    Twenties,
    Mauve,
    Radio,
    Bluechrome,
    Dramatic,
    PastelPink,
    Obsidian,
    Pixelate,
    Posterize,
    Sepia,
    Vignette,
    Temperature,
}

export struct SettingCursorTracker {
    enable-tracking: bool,
    region-width: int,
    region-height: int,
    debounce-radius: int,
    stable-radius: int,
    fast-moving-duration: int,
    zoom-transition-duration: int,
    reposition-transition-duration: int,
    reposition_edge_threshold: float,
    max-stable-region-duration: int,
    zoom_in_transition_type: TransitionType,
    zoom_out_transition_type: TransitionType,
}

export struct SettingRecorder {
    save-dir: string,
    include-cursor: bool,
    enable-denoise: bool,
    convert-to-mono: bool,
    fps: Fps,
    resolution: Resolution,
}

export enum BackgroundRemoverModel {
    Modnet,
    Rmbg14,
}

export struct SettingBackgroundRemover {
    enable: bool,
    model: BackgroundRemoverModel,
    modnet-path: string,
    rmbg14-path: string,
}

export enum MixPositionWithPaddingTag {
    TopLeft,
    TopRight,
    BottomLeft,
    BottomRight,
}

export struct MixPositionWithPadding {
    tag:  MixPositionWithPaddingTag,
    padding1: int,
    padding2: int,
}

export struct SettingCamera {
    fps: int,
    resolution: Resolution,
    zoom: float,
    pos: MixPositionWithPadding,
    border-size: int,
    border-color-index: int,
    border_color: string,
    mirror-horizontal: bool,

    is-circle-shape: bool,
    cropping-x: float,
    cropping-y: float,
    rect-cropping-width: int,
    rect-cropping-height: int,
    circle-cropping-radius: int,

    background-remover: SettingBackgroundRemover,
}

export struct SettingControl {
    screen: string,

    audio: string,
    audio-gain: float,
    enable-audio: bool,

    speaker-gain: float,
    enable-speaker: bool,

    camera: string,
    enable-camera: bool,
    camera-setting: SettingCamera,

    enable-stats: bool,
    enable-preview: bool,

    realtime_image-effect: RealtimeImageEffect,
}

export struct SettingPlayer {
    id: string,
    current-time: string,
    end-time: string,
    sound: int,
}

export struct SettingShareScreenClient {
    enable-auth: bool,
    auth-token: string,
    server-addr: string,
}

export struct RTCIceServer {
    url: string,
    username: string,
    credential: string,
}

export struct SettingShareScreen {
    save-mp4: bool,

    listen-addr: string,
    auth-token: string,

    enable-turn-server: bool,
    turn-server: RTCIceServer,

    enable-stun-server: bool,
    stun-server: RTCIceServer,

    host-ips: [string],
    disable-host-ipv6: bool,

    enable-https: bool,
    cert-file: string,
    key-file: string,
}

export struct SettingPushStream {
    save-mp4: bool,
    server-addr: string,
    app: string,
    stream-key: string,
    query-params: string,
}

export struct StatsInfo {
    fps: float,
    loss: float,
    total: int,
    share-screen-connections: int,
}

export enum RecordStatus{
    Stopped,
    Recording,
}

export enum SourceType {
    Audio,
    Video,
    Camera,
}

export struct Source{
    ty: SourceType,
    name: string,
}

export struct HistoryEntry {
    id: string,
    file: string,
    size: string,
    duration: string,
    status: string,
}

export enum ConnectionStatus {
    Disconnected,
    Connecting,
    Connected,
}

export enum DownloaderState {
    UnStart,
    Downloading,
    Finished,
    Failed,
    Cancelled,
}

export struct Downloader {
    state: DownloaderState,
    progress: float,
    url: string,
    filename: string,
}

//////////////////////////////// Logic Struct End  ////////////////////////////////

import { PlaylistItem } from "base/def.slint";

export global Store {
    in-out property <DeviceType> device-type: DeviceType.Desktop;
    in-out property <bool> is-first-run;
    in-out property <bool> is-show-landing-page;
    in-out property <bool> is-show-help-btn;
    in-out property <bool> is-show-remove-caches-btn;

    // desktop
    in-out property <TabIndex> previous-tab-index: TabIndex.Home;
    in-out property <TabIndex> current-tab-index: TabIndex.Home;
    in-out property <PopupIndex> current-popup-index: PopupIndex.None;
    in-out property <SettingDetailIndex> current-setting-detail-index: SettingDetailIndex.Preference;

    // android
    in-out property <MobileTabIndex> previous-mobile-tab-index: MobileTabIndex.Home;
    in-out property <MobileTabIndex> current-mobile-tab-index: MobileTabIndex.Home;
    in-out property <MobileSettingDetailIndex> current-mobile-setting-detail-index: MobileSettingDetailIndex.Preference;

    in-out property <SettingPreference> setting-preference: {
        win-width: 800,
        win-height: 640,
        font-size: "16",
        font-family: "Source Han Sans CN",
        language: "en",
        always-on-top: false,
        no-frame: true,
        is-dark: false,
    };

    //////////////////////////////// Logic Start ////////////////////////////////
    in-out property <bool> is-cn: setting-preference.language == "cn";
    in-out property <RecordStatus> record-status: RecordStatus.Stopped;
    in-out property <FeatureType> feature-type: FeatureType.Other;
    in-out property <ProcessMode> process-mode: ProcessMode.RecordScreen;
    in-out property <string> save-dir;
    in-out property <bool> never-recording-once: true;

    in-out property <int> record-duration;
    in-out property <string> final-video-path;
    in-out property <image> preview-image;
    in-out property <int> audio-db: -60;
    in-out property <int> speaker-audio-db: -60;
    in-out property <bool> start-recording-timer;

    in-out property <[string]> audio-sources: ["sound-card-1", "sound-card-2"];
    in-out property <[string]> video-sources: ["eDP-1", "eDP-2"];
    in-out property <[string]> camera-sources: ["camera-1", "camera-2"];

    in-out property <[Source]> sources: [
        { ty: SourceType.Audio, name: "sound-card-2" },
        { ty: SourceType.Video, name: "eDP-1" },
        { ty: SourceType.Camera, name: "camera-2" },
    ];

    in-out property <StatsInfo> stats-info: {
        fps: 0.0,
        loss: 0.0,
        total: 0,
    };

    in-out property <SettingControl> setting-control:  {
        screen: sources[1].name,
        audio: sources[0].name,
        audio-gain: -2,
        enable-audio: true,
        speaker-gain: 2,
        enable-speaker: true,
        camera: sources[2].name,
        enable-camera: true,
        camera-setting: {
            border-size: 3,
            is-circle-shape: false,
            rect-cropping-width: 150,
            rect-cropping-height: 150,
            circle-cropping-radius: 150,
            cropping-x: 0.5,
            cropping-y: 0.5,
        }
    };

    in-out property <SettingShareScreen> setting-share-screen;
    in-out property <string> setting-share-screen-cert-file;
    in-out property <string> setting-share-screen-key-file;

    in-out property <SettingPushStream> setting-push-stream;

    in-out property <bool> is-show-camera-setting-dialog;
    in-out property <SettingCamera> camera-setting-cache;
    in-out property <image> camera-setting-dialog-image;
    in-out property <[Downloader]> camera-background-remover-models-dowloader: [{ }, { }];
    in-out property <[color]> camera-cropping-area-border-colors: [
        Colors.white,
        Colors.black,
        Colors.gray,
        Colors.red,
        Colors.orange,
        Colors.yellow,
        Colors.green,
        Colors.blue,
        Colors.cyan,
        Colors.pink
    ];

    in-out property <[HistoryEntry]> history-entries: [
        { file: "file-1", size: "10M", duration: "4:00" },
        { file: "file-1", size: "100M" },
    ];

    in-out property <image> player-image;
    in-out property <float> player-progress;
    in-out property <bool> player-is-playing;
    in-out property <SettingPlayer> setting-player: { current-time: "00:00", end-time: "4:00", sound: 50 };

    in-out property <[PlaylistItem]> playlist-entries: [
        { title: "Video1", duration: "3:45" },
        { title: "Video2", duration: "4:20" },
    ];

    in-out property <image> share-screen-player-image;
    in-out property <int> share-screen-playing-duration;
    in-out property <bool> share-screen-is-playing-cache;
    in-out property <ConnectionStatus> share-screen-client-connection-status: ConnectionStatus.Disconnected;

    in-out property <bool> is-show-realtime-image-effect-dialog;

    //////////////////////////////// Logic End  ////////////////////////////////
}
